// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_c2_half_adder (
  input  wire a,
  input  wire b,
  output wire w_0,
  output wire w_1
);

  xor g_xor1(w_0, a, b);
  and g_and1(w_1, a, b);

endmodule // gc_c2_half_adder
`default_nettype wire