-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_c3_sr_latch is
  Port (
    s : in STD_LOGIC;
    r : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_c3_sr_latch;

architecture Behavioral of gc_c3_sr_latch is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  -- SR-Latch dut (cross-coupled NOR)
  w_0_q  <= w_1_q nor r;
  w_1_q <= w_0_q  nor s;

  w_0 <= w_0_q;
  w_1 <= w_1_q;

end Behavioral;