-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_m3_counter_gate is
  Port (
    clk : in STD_LOGIC;
    clrn : in STD_LOGIC;
    ldn : in STD_LOGIC;
    enp : in STD_LOGIC;
    ent : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    w_2 : out STD_LOGIC
  );
end gc_m3_counter_gate;

architecture Behavioral of gc_m3_counter_gate is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_ctr_q2 : STD_LOGIC := '0';
  signal w_ctr_q3 : STD_LOGIC := '0';
  signal w_ctr_rco : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal cnt_ctr : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  w_2_q <= w_0 and w_1; -- and1

  w_2 <= w_2_q;

  -- Sequential / registered logic
  -- 74HC161 ctr
  process(clk, clrn)
  begin
    if    clrn = '0'             then cnt_ctr <= (others => '0');
    elsif rising_edge(clk) then
      if    ldn  = '0'                       then cnt_ctr <= d3 & d2 & d1 & d0;
      elsif enp  = '1' and ent = '1'      then cnt_ctr <= std_logic_vector(unsigned(cnt_ctr) + 1);
      end if;
    end if;
  end process; -- 74HC161 ctr
  w_0 <= cnt_ctr(0);
  w_1 <= cnt_ctr(1);
  w_ctr_q2 <= cnt_ctr(2);
  w_ctr_q3 <= cnt_ctr(3);
  w_ctr_rco  <= ent when unsigned(cnt_ctr) = 15 else '0';

end Behavioral;