// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_s7_hc161_vs_hc163 (
  input  wire clk,
  input  wire clrn,
  input  wire enp,
  input  wire ent,
  input  wire ldn,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  output wire w_0,
  output wire w_1,
  output wire w_2,
  output wire w_3,
  output wire w_4,
  output wire w_5,
  output wire w_6,
  output wire w_7
);

  wire w_ctr161_rco, w_ctr163_rco;

  reg [3:0] cnt_ctr161;
  reg [3:0] cnt_ctr163;

  // Sequential logic
  // 74HC161 ctr161
  always @(posedge clk or negedge clrn) begin
    if      (!clrn)               cnt_ctr161 <= 4'd0;
    else if (!ldn)                cnt_ctr161 <= {d3,d2,d1,d0};
    else if (enp && ent)       cnt_ctr161 <= cnt_ctr161 + 1'b1;
  end // 74HC161 ctr161
  assign w_0 = cnt_ctr161[0];
  assign w_1 = cnt_ctr161[1];
  assign w_2 = cnt_ctr161[2];
  assign w_3 = cnt_ctr161[3];
  assign w_ctr161_rco  = ent & (cnt_ctr161 == 4'd15);
  // 74HC163 ctr163
  always @(posedge clk) begin
    if      (!clrn)               cnt_ctr163 <= 4'd0;
    else if (!ldn)                cnt_ctr163 <= {d3,d2,d1,d0};
    else if (enp && ent)       cnt_ctr163 <= cnt_ctr163 + 1'b1;
  end // 74HC163 ctr163
  assign w_4 = cnt_ctr163[0];
  assign w_5 = cnt_ctr163[1];
  assign w_6 = cnt_ctr163[2];
  assign w_7 = cnt_ctr163[3];
  assign w_ctr163_rco  = ent & (cnt_ctr163 == 4'd15);

endmodule // gc_s7_hc161_vs_hc163
`default_nettype wire