-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s7_hc161_vs_hc163 is
  Port (
    clk : in STD_LOGIC;
    clrn : in STD_LOGIC;
    enp : in STD_LOGIC;
    ent : in STD_LOGIC;
    ldn : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_7 : out STD_LOGIC
  );
end gc_s7_hc161_vs_hc163;

architecture Behavioral of gc_s7_hc161_vs_hc163 is
  signal w_ctr161_rco : STD_LOGIC := '0';
  signal w_ctr163_rco : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  signal cnt_ctr161 : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
  signal cnt_ctr163 : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_6 <= w_6_q;
  w_7 <= w_7_q;

  -- Sequential / registered logic
  -- 74HC161 ctr161
  process(clk, clrn)
  begin
    if    clrn = '0'             then cnt_ctr161 <= (others => '0');
    elsif rising_edge(clk) then
      if    ldn  = '0'                       then cnt_ctr161 <= d3 & d2 & d1 & d0;
      elsif enp  = '1' and ent = '1'      then cnt_ctr161 <= std_logic_vector(unsigned(cnt_ctr161) + 1);
      end if;
    end if;
  end process; -- 74HC161 ctr161
  w_0_q <= cnt_ctr161(0);
  w_1_q <= cnt_ctr161(1);
  w_2_q <= cnt_ctr161(2);
  w_3_q <= cnt_ctr161(3);
  w_ctr161_rco  <= ent when unsigned(cnt_ctr161) = 15 else '0';
  -- 74HC163 ctr163
  process(clk)
  begin
    if rising_edge(clk) then
      if    clrn = '0'                       then cnt_ctr163 <= (others => '0');
      elsif ldn  = '0'                       then cnt_ctr163 <= d3 & d2 & d1 & d0;
      elsif enp  = '1' and ent = '1'      then cnt_ctr163 <= std_logic_vector(unsigned(cnt_ctr163) + 1);
      end if;
    end if;
  end process; -- 74HC163 ctr163
  w_4_q <= cnt_ctr163(0);
  w_5_q <= cnt_ctr163(1);
  w_6_q <= cnt_ctr163(2);
  w_7_q <= cnt_ctr163(3);
  w_ctr163_rco  <= ent when unsigned(cnt_ctr163) = 15 else '0';

end Behavioral;