-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_3_shift_pipeline is
  Port (
    clk : in STD_LOGIC;
    clrn : in STD_LOGIC;
    s0 : in STD_LOGIC;
    s1 : in STD_LOGIC;
    sr : in STD_LOGIC;
    sl : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    stcp : in STD_LOGIC;
    mr : in STD_LOGIC;
    oe : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_7 : out STD_LOGIC;
    w_8 : out STD_LOGIC;
    w_9 : out STD_LOGIC;
    w_10 : out STD_LOGIC;
    w_11 : out STD_LOGIC
  );
end gc_v2_3_shift_pipeline;

architecture Behavioral of gc_v2_3_shift_pipeline is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
  signal w_9_q : STD_LOGIC := '0';
  signal w_10_q : STD_LOGIC := '0';
  signal w_11_q : STD_LOGIC := '0';
  signal reg_dut_194 : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
  signal shift_dut_595 : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
  signal latch_dut_595 : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_6 <= w_6_q;
  w_7 <= w_7_q;
  w_8 <= w_8_q;
  w_9 <= w_9_q;
  w_10 <= w_10_q;
  w_11 <= w_11_q;

  -- Sequential / registered logic
  -- 74HC194 dut_194
  process(clk, clrn)
  begin
    if clrn = '0' then reg_dut_194 <= (others => '0');
    elsif rising_edge(clk) then
      case STD_LOGIC_VECTOR'(s1 & s0) is
        when "01" => reg_dut_194 <= sr & reg_dut_194(3 downto 1);
        when "10" => reg_dut_194 <= reg_dut_194(2 downto 0) & sl;
        when "11" => reg_dut_194 <= d3 & d2 & d1 & d0;
        when others => null;
      end case;
    end if;
  end process; -- 74HC194 dut_194
  w_0_q <= reg_dut_194(0);
  w_1_q <= reg_dut_194(1);
  w_2_q <= reg_dut_194(2);
  w_3_q <= reg_dut_194(3);
  -- 74HC595 dut_595
  process(clk, mr)
  begin
    if mr = '0' then shift_dut_595 <= (others => '0');
    elsif rising_edge(clk) then shift_dut_595 <= shift_dut_595(6 downto 0) & w_3_q;
    end if;
  end process;
  process(stcp)
  begin
    if rising_edge(stcp) then latch_dut_595 <= shift_dut_595;
    end if;
  end process; -- 74HC595 dut_595
  w_4_q <= 'Z' when oe = '1' else latch_dut_595(0);
  w_5_q <= 'Z' when oe = '1' else latch_dut_595(1);
  w_6_q <= 'Z' when oe = '1' else latch_dut_595(2);
  w_7_q <= 'Z' when oe = '1' else latch_dut_595(3);
  w_8_q <= 'Z' when oe = '1' else latch_dut_595(4);
  w_9_q <= 'Z' when oe = '1' else latch_dut_595(5);
  w_10_q <= 'Z' when oe = '1' else latch_dut_595(6);
  w_11_q <= 'Z' when oe = '1' else latch_dut_595(7);

end Behavioral;