-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_4_ram_readback is
  Port (
    a0 : in STD_LOGIC;
    a1 : in STD_LOGIC;
    a2 : in STD_LOGIC;
    a3 : in STD_LOGIC;
    a4 : in STD_LOGIC;
    a5 : in STD_LOGIC;
    a6 : in STD_LOGIC;
    a7 : in STD_LOGIC;
    di0 : in STD_LOGIC;
    di1 : in STD_LOGIC;
    di2 : in STD_LOGIC;
    di3 : in STD_LOGIC;
    di4 : in STD_LOGIC;
    di5 : in STD_LOGIC;
    di6 : in STD_LOGIC;
    di7 : in STD_LOGIC;
    we : in STD_LOGIC;
    cs : in STD_LOGIC;
    oe : in STD_LOGIC;
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_7 : out STD_LOGIC;
    w_8 : out STD_LOGIC
  );
end gc_v2_4_ram_readback;

architecture Behavioral of gc_v2_4_ram_readback is
  signal w_9 : STD_LOGIC := '0';
  signal w_10 : STD_LOGIC := '0';
  signal w_11 : STD_LOGIC := '0';
  signal w_12 : STD_LOGIC := '0';
  signal w_13 : STD_LOGIC := '0';
  signal w_14 : STD_LOGIC := '0';
  signal w_15 : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  type t_ram_ram is array (0 to 255) of STD_LOGIC_VECTOR(7 downto 0);
  signal ram_ram : t_ram_ram := (others => (others => '0'));
begin

  -- RAM256 ram
  process(a0, a1, a2, a3, a4, a5, a6, a7, di0, di1, di2, di3, di4, di5, di6, di7, we, cs) -- async write (transparent latch)
  begin
    if cs = '0' and we = '0' then
      ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0)))) <= std_logic_vector'(di7 & di6 & di5 & di4 & di3 & di2 & di1 & di0);
    end if;
  end process;
  process(a0, a1, a2, a3, a4, a5, a6, a7, oe, cs, ram_ram) -- read
  begin
    w_8_q <= 'Z'; w_9 <= 'Z'; w_10 <= 'Z'; w_11 <= 'Z'; w_12 <= 'Z'; w_13 <= 'Z'; w_14 <= 'Z'; w_15 <= 'Z';
    if cs = '0' and oe = '0' then
      w_8_q <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(0);
      w_9 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(1);
      w_10 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(2);
      w_11 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(3);
      w_12 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(4);
      w_13 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(5);
      w_14 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(6);
      w_15 <= ram_ram(to_integer(unsigned(std_logic_vector'(a7 & a6 & a5 & a4 & a3 & a2 & a1 & a0))))(7);
    end if;
  end process; -- RAM256 ram

  w_8 <= w_8_q;
  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_6 <= w_6_q;
  w_7 <= w_7_q;

  -- Sequential / registered logic
  -- REG8 reg
  process(clk, rst)
  begin
    if rst = '1' then
      w_0_q <= '0'; w_1_q <= '0'; w_2_q <= '0'; w_3_q <= '0'; w_4_q <= '0'; w_5_q <= '0'; w_6_q <= '0'; w_7_q <= '0';
    elsif rising_edge(clk) then
      w_0_q <= w_8_q; w_1_q <= w_9; w_2_q <= w_10; w_3_q <= w_11; w_4_q <= w_12; w_5_q <= w_13; w_6_q <= w_14; w_7_q <= w_15;
    end if;
  end process; -- REG8 reg

end Behavioral;