// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_1_mux_fabric (
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  input  wire d4,
  input  wire d5,
  input  wire d6,
  input  wire d7,
  input  wire d8,
  input  wire d9,
  input  wire d10,
  input  wire d11,
  input  wire d12,
  input  wire d13,
  input  wire d14,
  input  wire d15,
  input  wire s0,
  input  wire s1,
  input  wire s2,
  input  wire m0,
  input  wire m1,
  output wire w_8,
  output wire w_9
);

  wire w_0, w_1, w_2, w_3, w_4, w_6, w_5, w_7;

  assign w_0 = 1'b0; // CONST_LOW
  assign w_1 = 1'b0; // CONST_LOW
  assign w_2 = 1'b0; // CONST_LOW
  assign w_3 = 1'b0; // CONST_LOW
  // 74HC151 mux_lo
  assign w_4  = w_0 ? 1'b0 : ({s2,s1,s0}==3'd0 ? d0 : {s2,s1,s0}==3'd1 ? d1 : {s2,s1,s0}==3'd2 ? d2 : {s2,s1,s0}==3'd3 ? d3 : {s2,s1,s0}==3'd4 ? d4 : {s2,s1,s0}==3'd5 ? d5 : {s2,s1,s0}==3'd6 ? d6 : {s2,s1,s0}==3'd7 ? d7 : 1'b0);
  assign w_6 = ~w_4;
  // 74HC151 mux_hi
  assign w_5  = w_1 ? 1'b0 : ({s2,s1,s0}==3'd0 ? d8 : {s2,s1,s0}==3'd1 ? d9 : {s2,s1,s0}==3'd2 ? d10 : {s2,s1,s0}==3'd3 ? d11 : {s2,s1,s0}==3'd4 ? d12 : {s2,s1,s0}==3'd5 ? d13 : {s2,s1,s0}==3'd6 ? d14 : {s2,s1,s0}==3'd7 ? d15 : 1'b0);
  assign w_7 = ~w_5;
  // 74HC153 mux_merge
  assign w_8 = w_2 ? 1'b0 : ({m1,m0}==2'd0 ? w_4 : {m1,m0}==2'd1 ? w_5 : {m1,m0}==2'd2 ? w_6 : {m1,m0}==2'd3 ? w_7 : 1'b0);
  assign w_9 = w_3 ? 1'b0 : ({m1,m0}==2'd0 ? d0 : {m1,m0}==2'd1 ? d7 : {m1,m0}==2'd2 ? d8 : {m1,m0}==2'd3 ? d15 : 1'b0);

endmodule // gc_v2_1_mux_fabric
`default_nettype wire