// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_12_nested_halfadder_parent (
  input  wire a,
  input  wire b,
  output wire w_0,
  output wire w_1,
  output wire w_2
);

  wire w_3, w_4;

  xor g_parent_flat_ha0_flat_xor1(w_3, a, b);
  and g_parent_flat_ha0_flat_and1(w_4, a, b);
  or g_parent_flat_or_any(w_0, w_3, w_4);
  or g_raw_or(w_1, a, b);
  xor g_xor_diff(w_2, w_0, w_1);

endmodule // gc_v2_12_nested_halfadder_parent
`default_nettype wire