-- Generated by LogicSim
-- HDL EXPORT BLOCKED — Error: Nested custom IC "CIC_PARENT_HALF_ADDER" already contains its own custom IC hierarchy. The current rollout allows only one additional canonical combinational level.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity gc_v2_13_deep_nested_halfadder_boundary is
end gc_v2_13_deep_nested_halfadder_boundary;

architecture Behavioral of gc_v2_13_deep_nested_halfadder_boundary is
begin
  -- no logic — export blocked
end Behavioral;