// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_15_ram_decode_capture_bus (
  input  wire a0,
  input  wire a1,
  input  wire a2,
  input  wire g1,
  input  wire di0,
  input  wire di1,
  input  wire di2,
  input  wire di3,
  input  wire di4,
  input  wire di5,
  input  wire di6,
  input  wire di7,
  input  wire we,
  input  wire cs,
  input  wire oe,
  input  wire le373,
  input  wire oe373,
  input  wire clk,
  input  wire rst,
  output wire w_13,
  output wire w_14,
  output reg  w_15,
  output reg  w_16,
  output reg  w_17,
  output reg  w_18,
  output reg  w_2
);

  wire w_0, w_1, w_11, w_dec_y1, w_dec_y2, w_dec_y3, w_dec_y4, w_12, w_dec_y6, w_dec_y7, w_10, w_mux_yn, w_lat373_q1, w_lat373_q2, w_lat373_q3, w_lat373_q4, w_lat373_q6, w_lat373_q7;

  reg  w_3, w_4, w_5, w_6, w_7, w_8, w_9;

  reg [7:0] ram_ram [0:255];
  integer ram_ram_init_idx;
  initial begin
    for (ram_ram_init_idx = 0; ram_ram_init_idx < 256; ram_ram_init_idx = ram_ram_init_idx + 1) begin
      ram_ram[ram_ram_init_idx] = 8'h00;
    end
  end
  reg [7:0] latch_lat373;

  assign w_0 = 1'b0; // CONST_LOW
  assign w_1 = 1'b1; // CONST_HIGH
  // RAM256 ram
  /* verilator lint_off LATCH */
  always @(*) begin // async write (transparent latch)
    if (cs == 1'b0 && we == 1'b0)
      ram_ram[{w_0, w_0, w_0, w_0, w_0, a2, a1, a0}] = {di7, di6, di5, di4, di3, di2, di1, di0};
  end
  /* verilator lint_on LATCH */
  always @(*) begin // read
    if (cs == 1'b0 && oe == 1'b0)
      {w_9, w_8, w_7, w_6, w_5, w_4, w_3, w_2} = ram_ram[{w_0, w_0, w_0, w_0, w_0, a2, a1, a0}];
    else
      {w_9, w_8, w_7, w_6, w_5, w_4, w_3, w_2} = 8'hzz;
  end // RAM256 ram
  // 74HC138 dec
  assign w_11 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd0));
  assign w_dec_y1 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd1));
  assign w_dec_y2 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd2));
  assign w_dec_y3 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd3));
  assign w_dec_y4 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd4));
  assign w_12 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd5));
  assign w_dec_y6 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd6));
  assign w_dec_y7 = ~((g1 & ~w_0 & ~w_0) & ({a2, a1, a0} == 3'd7));
  // 74HC151 mux
  assign w_10  = w_0 ? 1'b0 : ({a2,a1,a0}==3'd0 ? w_2 : {a2,a1,a0}==3'd1 ? w_3 : {a2,a1,a0}==3'd2 ? w_4 : {a2,a1,a0}==3'd3 ? w_5 : {a2,a1,a0}==3'd4 ? w_6 : {a2,a1,a0}==3'd5 ? w_7 : {a2,a1,a0}==3'd6 ? w_8 : {a2,a1,a0}==3'd7 ? w_9 : 1'b0);
  assign w_mux_yn = ~w_10;

  // Sequential logic
  // 74HC373 lat373
  /* verilator lint_off LATCH */
  always @(*) begin
    if (le373) latch_lat373 = {w_9,w_8,w_7,w_6,w_5,w_4,w_3,w_2};
  end /* verilator lint_on LATCH */ // 74HC373 lat373
  assign w_13 = oe373 ? 1'bz : latch_lat373[0];
  assign w_lat373_q1 = oe373 ? 1'bz : latch_lat373[1];
  assign w_lat373_q2 = oe373 ? 1'bz : latch_lat373[2];
  assign w_lat373_q3 = oe373 ? 1'bz : latch_lat373[3];
  assign w_lat373_q4 = oe373 ? 1'bz : latch_lat373[4];
  assign w_14 = oe373 ? 1'bz : latch_lat373[5];
  assign w_lat373_q6 = oe373 ? 1'bz : latch_lat373[6];
  assign w_lat373_q7 = oe373 ? 1'bz : latch_lat373[7];
  // REG4 reg
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_15 <= 1'b0; w_16 <= 1'b0; w_17 <= 1'b0; w_18 <= 1'b0;
    end else if (w_1) begin
      w_15 <= w_10; w_16 <= w_11; w_17 <= w_12; w_18 <= w_2;
    end
  end // REG4 reg

endmodule // gc_v2_15_ram_decode_capture_bus
`default_nettype wire