// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_7_bus_conflict_system (
  input  wire a_clk,
  input  wire a_oe,
  input  wire a_d0,
  input  wire a_d1,
  input  wire b_clk,
  input  wire b_oe,
  input  wire b_d0,
  input  wire b_d1,
  output wire w_3,
  output reg  w_4,
  output reg  w_5,
  output reg  w_6,
  output reg  w_7,
  output wire w_10,
  output wire w_12
);

  wire w_1, w_0, w_2, w_master_a_q1, w_master_a_q2, w_master_a_q3, w_master_a_q4, w_master_a_q5, w_master_a_q6, w_master_a_q7, w_master_b_q1, w_master_b_q2, w_master_b_q3, w_master_b_q4, w_master_b_q5, w_master_b_q6, w_master_b_q7, w_8, w_9, w_11;

  reg  w_shadow_a_q2, w_shadow_a_q3, w_shadow_b_q2, w_shadow_b_q3;

  reg [7:0] reg_master_a;
  reg [7:0] reg_master_b;

  assign w_1 = 1'b1; // CONST_HIGH
  assign w_0 = 1'b0; // CONST_LOW
  not g_not_a_oe(w_8, a_oe);
  not g_not_b_oe(w_9, b_oe);
  and g_oe_overlap_gate(w_10, w_8, w_9);
  xor g_bit0_diff(w_11, w_4, w_6);
  and g_conflict0_gate(w_12, w_11, w_10);

  // Sequential logic
  // 74HC374 master_a
  always @(posedge a_clk) begin
    reg_master_a <= {w_0,w_0,w_0,w_0,w_0,w_0,a_d1,a_d0};
  end // 74HC374 master_a
  assign w_2 = a_oe ? 1'bz : reg_master_a[0];
  assign w_master_a_q1 = a_oe ? 1'bz : reg_master_a[1];
  assign w_master_a_q2 = a_oe ? 1'bz : reg_master_a[2];
  assign w_master_a_q3 = a_oe ? 1'bz : reg_master_a[3];
  assign w_master_a_q4 = a_oe ? 1'bz : reg_master_a[4];
  assign w_master_a_q5 = a_oe ? 1'bz : reg_master_a[5];
  assign w_master_a_q6 = a_oe ? 1'bz : reg_master_a[6];
  assign w_master_a_q7 = a_oe ? 1'bz : reg_master_a[7];
  // REG4 shadow_a
  always @(posedge a_clk or posedge w_0) begin
    if (w_0) begin
      w_4 <= 1'b0; w_5 <= 1'b0; w_shadow_a_q2 <= 1'b0; w_shadow_a_q3 <= 1'b0;
    end else if (w_1) begin
      w_4 <= a_d0; w_5 <= a_d1; w_shadow_a_q2 <= w_0; w_shadow_a_q3 <= w_0;
    end
  end // REG4 shadow_a
  // 74HC374 master_b
  always @(posedge b_clk) begin
    reg_master_b <= {w_0,w_0,w_0,w_0,w_0,w_0,b_d1,b_d0};
  end // 74HC374 master_b
  assign w_3 = b_oe ? 1'bz : reg_master_b[0];
  assign w_master_b_q1 = b_oe ? 1'bz : reg_master_b[1];
  assign w_master_b_q2 = b_oe ? 1'bz : reg_master_b[2];
  assign w_master_b_q3 = b_oe ? 1'bz : reg_master_b[3];
  assign w_master_b_q4 = b_oe ? 1'bz : reg_master_b[4];
  assign w_master_b_q5 = b_oe ? 1'bz : reg_master_b[5];
  assign w_master_b_q6 = b_oe ? 1'bz : reg_master_b[6];
  assign w_master_b_q7 = b_oe ? 1'bz : reg_master_b[7];
  // REG4 shadow_b
  always @(posedge b_clk or posedge w_0) begin
    if (w_0) begin
      w_6 <= 1'b0; w_7 <= 1'b0; w_shadow_b_q2 <= 1'b0; w_shadow_b_q3 <= 1'b0;
    end else if (w_1) begin
      w_6 <= b_d0; w_7 <= b_d1; w_shadow_b_q2 <= w_0; w_shadow_b_q3 <= w_0;
    end
  end // REG4 shadow_b

endmodule // gc_v2_7_bus_conflict_system
`default_nettype wire