-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_1_mux_fabric is
  Port (
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    d4 : in STD_LOGIC;
    d5 : in STD_LOGIC;
    d6 : in STD_LOGIC;
    d7 : in STD_LOGIC;
    d8 : in STD_LOGIC;
    d9 : in STD_LOGIC;
    d10 : in STD_LOGIC;
    d11 : in STD_LOGIC;
    d12 : in STD_LOGIC;
    d13 : in STD_LOGIC;
    d14 : in STD_LOGIC;
    d15 : in STD_LOGIC;
    s0 : in STD_LOGIC;
    s1 : in STD_LOGIC;
    s2 : in STD_LOGIC;
    m0 : in STD_LOGIC;
    m1 : in STD_LOGIC;
    w_8 : out STD_LOGIC;
    w_9 : out STD_LOGIC
  );
end gc_v2_1_mux_fabric;

architecture Behavioral of gc_v2_1_mux_fabric is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_2 : STD_LOGIC := '0';
  signal w_3 : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_6 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_7 : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
  signal w_9_q : STD_LOGIC := '0';
begin

  w_0 <= '0'; -- CONST_LOW
  w_1 <= '0'; -- CONST_LOW
  w_2 <= '0'; -- CONST_LOW
  w_3 <= '0'; -- CONST_LOW
  -- 74HC151 mux_lo
  w_4 <= '0' when w_0 = '1' else
         d0 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("000") else
         d1 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("001") else
         d2 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("010") else
         d3 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("011") else
         d4 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("100") else
         d5 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("101") else
         d6 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("110") else
         d7;
  w_6 <= not w_4;
  -- 74HC151 mux_hi
  w_5 <= '0' when w_1 = '1' else
         d8 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("000") else
         d9 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("001") else
         d10 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("010") else
         d11 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("011") else
         d12 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("100") else
         d13 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("101") else
         d14 when STD_LOGIC_VECTOR'(s2 & s1 & s0) = STD_LOGIC_VECTOR'("110") else
         d15;
  w_7 <= not w_5;
  -- 74HC153 mux_merge
  w_8_q <= '0' when w_2 = '1' else
         w_4 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("00") else
         w_5 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("01") else
         w_6 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("10") else
         w_7;
  w_9_q <= '0' when w_3 = '1' else
         d0 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("00") else
         d7 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("01") else
         d8 when STD_LOGIC_VECTOR'(m1 & m0) = STD_LOGIC_VECTOR'("10") else
         d15;

  w_8 <= w_8_q;
  w_9 <= w_9_q;

end Behavioral;