// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_8_sequential_feedback (
  input  wire clk,
  input  wire rst,
  input  wire en,
  input  wire d,
  input  wire d2,
  input  wire d3,
  output reg  w_2,
  output reg  w_0,
  output reg  w_1,
  output wire w_3
);

  wire w_4, w_5, w_6, w_ff1_q_n, w_ff2_q_n, w_ff3_q_n;

  assign w_4 = en ? w_0 : d; // MUX2 g_mux1
  assign w_5 = en ? w_1 : d2; // MUX2 g_mux2
  xor g_g_xor_fb(w_3, w_2, w_0);
  assign w_6 = en ? w_3 : d3; // MUX2 g_mux3

  // Sequential logic
  always @(posedge clk or posedge rst) begin
    if (rst) w_2 <= 1'b0;
    else        w_2 <= w_4;
  end // D-FF/R ff1
  assign w_ff1_q_n = ~w_2;
  always @(posedge clk or posedge rst) begin
    if (rst) w_0 <= 1'b0;
    else        w_0 <= w_5;
  end // D-FF/R ff2
  assign w_ff2_q_n = ~w_0;
  always @(posedge clk or posedge rst) begin
    if (rst) w_1 <= 1'b0;
    else        w_1 <= w_6;
  end // D-FF/R ff3
  assign w_ff3_q_n = ~w_1;

endmodule // gc_v2_8_sequential_feedback
`default_nettype wire