-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_2_datapath_slice is
  Port (
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    en : in STD_LOGIC;
    b0 : in STD_LOGIC;
    b1 : in STD_LOGIC;
    b2 : in STD_LOGIC;
    b3 : in STD_LOGIC;
    cin : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_11 : out STD_LOGIC;
    w_12 : out STD_LOGIC
  );
end gc_v2_2_datapath_slice;

architecture Behavioral of gc_v2_2_datapath_slice is
  signal w_7 : STD_LOGIC := '0';
  signal w_8 : STD_LOGIC := '0';
  signal w_9 : STD_LOGIC := '0';
  signal w_10 : STD_LOGIC := '0';
  signal w_alu_cout : STD_LOGIC := '0';
  signal w_alu_zero : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_11_q : STD_LOGIC := '0';
  signal w_12_q : STD_LOGIC := '0';
  signal cnt_phase : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  -- ALU4 alu
  process(w_0_q, w_1_q, w_2_q, w_3_q, b0, b1, b2, b3, w_4_q, w_5_q, w_6_q, cin)
    variable va  : unsigned(3 downto 0);
    variable vb  : unsigned(3 downto 0);
    variable vop : integer range 0 to 7;
    variable sum : unsigned(4 downto 0);
  begin
    va  := unsigned(STD_LOGIC_VECTOR'(w_3_q & w_2_q & w_1_q & w_0_q));
    vb  := unsigned(STD_LOGIC_VECTOR'(b3 & b2 & b1 & b0));
    vop := to_integer(unsigned(STD_LOGIC_VECTOR'(w_6_q & w_5_q & w_4_q)));
    sum := (others => '0');
    case vop is
      when 0 => sum := resize(va,5) + resize(vb,5) + (to_unsigned(0,4) & cin); -- ADD
      when 1 => sum := resize(va,5) - resize(vb,5) - (to_unsigned(0,4) & cin); -- SUB
      when 2 => sum(3 downto 0) := va and vb;                                   -- AND
      when 3 => sum(3 downto 0) := va or  vb;                                   -- OR
      when 4 => sum(3 downto 0) := va xor vb;                                   -- XOR
      when 5 => sum(3 downto 0) := not va;                                      -- NOT A
      when 6 => sum(0):='0'; sum(1):=va(0); sum(2):=va(1); sum(3):=va(2); sum(4):=va(3); -- SHL
      when 7 => sum(0):=va(1); sum(1):=va(2); sum(2):=va(3); sum(3):='0'; sum(4):=va(0); -- SHR
      when others => null;
    end case;
    w_7 <= sum(0); w_8 <= sum(1); w_9 <= sum(2); w_10 <= sum(3);
    w_alu_cout <= sum(4);
    if sum(3 downto 0) = x"0" then w_alu_zero <= '1'; else w_alu_zero <= '0'; end if;
  end process; -- ALU4 alu

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_6 <= w_6_q;
  w_11 <= w_11_q;
  w_12 <= w_12_q;

  -- Sequential / registered logic
  -- REG4 acc
  process(clk, rst)
  begin
    if rst = '1' then
      w_0_q <= '0'; w_1_q <= '0'; w_2_q <= '0'; w_3_q <= '0';
    elsif rising_edge(clk) then
      if en = '1' then
        w_0_q <= w_7; w_1_q <= w_8; w_2_q <= w_9; w_3_q <= w_10;
      end if;
    end if;
  end process; -- REG4 acc
  -- BIN_CTR7S phase
  process(clk, rst)
  begin
    if rst = '1' then
      cnt_phase <= (others => '0');
    elsif rising_edge(clk) then
      if en = '1' then
        cnt_phase <= std_logic_vector(unsigned(cnt_phase) + 1);
      end if;
    end if;
  end process; -- BIN_CTR7S phase
  w_4_q  <= cnt_phase(0);
  w_5_q  <= cnt_phase(1);
  w_6_q  <= cnt_phase(2);
  w_11_q  <= cnt_phase(3);
  w_12_q <= '1' when cnt_phase = "1111" else '0';

end Behavioral;