// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_2_datapath_slice (
  input  wire clk,
  input  wire rst,
  input  wire en,
  input  wire b0,
  input  wire b1,
  input  wire b2,
  input  wire b3,
  input  wire cin,
  output reg  w_0,
  output reg  w_1,
  output reg  w_2,
  output reg  w_3,
  output wire w_4,
  output wire w_5,
  output wire w_6,
  output wire w_11,
  output wire w_12
);

  reg  w_7, w_8, w_9, w_10, w_alu_cout, w_alu_zero;

  reg [3:0] cnt_phase;

  // ALU4 alu
  always @(*) begin : blk_alu
    reg [3:0] va, vb;
    reg [4:0] sum;
    va  = {w_3, w_2, w_1, w_0};
    vb  = {b3, b2, b1, b0};
    sum = 5'b0;
    case ({w_6, w_5, w_4})
      3'b000: sum = {1'b0, va} + {1'b0, vb} + {4'b0, cin}; // ADD
      3'b001: sum = {1'b0, va} - {1'b0, vb} - {4'b0, cin}; // SUB
      3'b010: sum = {1'b0, va & vb};                           // AND
      3'b011: sum = {1'b0, va | vb};                           // OR
      3'b100: sum = {1'b0, va ^ vb};                           // XOR
      3'b101: sum = {1'b0, ~va};                               // NOT A
      3'b110: sum = {va, 1'b0};                                // SHL (MSB→COUT)
      3'b111: sum = {va[0], 1'b0, va[3:1]};                   // SHR (LSB→COUT)
      default: sum = 5'b0;
    endcase
    w_7 = sum[0]; w_8 = sum[1]; w_9 = sum[2]; w_10 = sum[3];
    w_alu_cout = sum[4];
    w_alu_zero = (sum[3:0] == 4'b0) ? 1'b1 : 1'b0;
  end // ALU4 alu

  // Sequential logic
  // REG4 acc
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_0 <= 1'b0; w_1 <= 1'b0; w_2 <= 1'b0; w_3 <= 1'b0;
    end else if (en) begin
      w_0 <= w_7; w_1 <= w_8; w_2 <= w_9; w_3 <= w_10;
    end
  end // REG4 acc
  // BIN_CTR7S phase
  always @(posedge clk or posedge rst) begin
    if (rst)     cnt_phase <= 4'd0;
    else if (en) cnt_phase <= cnt_phase + 1'b1;
  end // BIN_CTR7S phase
  assign w_4  = cnt_phase[0];
  assign w_5  = cnt_phase[1];
  assign w_6  = cnt_phase[2];
  assign w_11  = cnt_phase[3];
  assign w_12 = (cnt_phase == 4'd15) ? 1'b1 : 1'b0;

endmodule // gc_v2_2_datapath_slice
`default_nettype wire