// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_11_custom_hc194_wrap (
  input  wire clk,
  input  wire clrn,
  input  wire s0,
  input  wire s1,
  input  wire sr,
  input  wire sl,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  output wire w_0,
  output wire w_1,
  output wire w_2,
  output wire w_3
);

  reg [3:0] reg_wrap_flat_dut;

  // Sequential logic
  // 74HC194 wrap_flat_dut
  always @(posedge clk or negedge clrn) begin
    if (!clrn) reg_wrap_flat_dut <= 4'b0;
    else case ({s1, s0})
      2'b01: reg_wrap_flat_dut <= {sr, reg_wrap_flat_dut[3:1]};
      2'b10: reg_wrap_flat_dut <= {reg_wrap_flat_dut[2:0], sl};
      2'b11: reg_wrap_flat_dut <= {d3,d2,d1,d0};
      default: ;
    endcase
  end // 74HC194 wrap_flat_dut
  assign w_0 = reg_wrap_flat_dut[0];
  assign w_1 = reg_wrap_flat_dut[1];
  assign w_2 = reg_wrap_flat_dut[2];
  assign w_3 = reg_wrap_flat_dut[3];

endmodule // gc_v2_11_custom_hc194_wrap
`default_nettype wire