// Generated by LogicSim
// HDL EXPORT BLOCKED — Error: Nested custom IC "CIC_PARENT_HALF_ADDER" already contains its own custom IC hierarchy. The current rollout allows only one additional canonical combinational level.
`default_nettype none

module gc_v2_13_deep_nested_halfadder_boundary;
  // no logic — export blocked
endmodule // gc_v2_13_deep_nested_halfadder_boundary
`default_nettype wire