import type { Circuit, GateInstance } from '../types';
import { gateRegistry } from '../registry/GateRegistry';

interface WireMap {
  /** portKey "gateId:portId" → signal name */
  byPort: Record<string, string>;
}

function sanitize(id: string) {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

// Gate types that have no direct Verilog equivalent and should be excluded from logic
const EXCLUDE_FROM_VERILOG = new Set([
  'CLOCK', 'PUSH_BTN', 'JUNCTION', 'TEXT_NOTE',
  'OUTPUT_LED_7SEG', 'DOT_MATRIX', 'STEPPER_MOTOR', 'ADC8',
  'ROM256', 'RAM256', 'CUSTOM_IC',
]);

function buildWireMap(circuit: Circuit): WireMap {
  const byPort: Record<string, string> = {};

  let swIdx = 0;
  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      const name = gate.label ? sanitize(gate.label) : `sw_${swIdx++}`;
      byPort[`${gate.id}:out`] = name;
    }
  }

  let wIdx = 0;
  for (const wire of Object.values(circuit.wires)) {
    const fromKey = `${wire.from.gateId}:${wire.from.portId}`;
    if (!byPort[fromKey]) {
      byPort[fromKey] = `w_${wIdx++}`;
    }
    byPort[`${wire.to.gateId}:${wire.to.portId}`] = byPort[fromKey];
  }

  let ledIdx = 0;
  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'OUTPUT_LED') {
      const inKey = `${gate.id}:in`;
      if (!byPort[inKey]) {
        const name = gate.label ? sanitize(gate.label) : `led_${ledIdx++}`;
        byPort[inKey] = name;
      }
    }
  }

  return { byPort };
}

export function generateVerilog(circuit: Circuit): string {
  const moduleName = sanitize(circuit.name) || 'circuit';
  const { byPort } = buildWireMap(circuit);

  const inputs:   string[] = [];
  const outputs:  string[] = [];
  const wires  = new Set<string>(); // combinational internal signals
  const regs   = new Set<string>(); // sequential (FF) internal signals
  const gateLines: string[] = [];
  const ffLines:   string[] = [];

  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      const name = byPort[`${gate.id}:out`] ?? `sw_${gate.id}`;
      inputs.push(name);
    } else if (gate.typeId === 'OUTPUT_LED') {
      const name = byPort[`${gate.id}:in`] ?? `led_${gate.id}`;
      outputs.push(name);
    } else if (!EXCLUDE_FROM_VERILOG.has(gate.typeId) && gateRegistry.has(gate.typeId)) {
      const def = gateRegistry.get(gate.typeId);

      // Collect internal signal declarations, split wire vs reg
      for (const out of def.outputs) {
        const k = `${gate.id}:${out.id}`;
        const wName = byPort[k];
        if (wName && !inputs.includes(wName) && !outputs.includes(wName)) {
          if (def.isSynchronous) regs.add(wName);
          else wires.add(wName);
        }
      }

      // Generate Verilog for this gate
      let line: string;
      if (gate.typeId === 'CONST_HIGH') {
        const s = byPort[`${gate.id}:out`];
        line = s ? `assign ${s} = 1'b1; // CONST_HIGH` : `// CONST_HIGH (unconnected)`;
      } else if (gate.typeId === 'CONST_LOW') {
        const s = byPort[`${gate.id}:out`];
        line = s ? `assign ${s} = 1'b0; // CONST_LOW` : `// CONST_LOW (unconnected)`;
      } else if (def.toVerilog) {
        line = def.toVerilog(gate, byPort);
      } else {
        line = defaultGateVerilog(gate, byPort);
      }

      // Multi-line support: indent each line
      const indented = line.split('\n').map(l => '  ' + l).join('\n');
      (def.isSynchronous ? ffLines : gateLines).push(indented);
    }
  }

  // Bug fix 1: any signal consumed by logic but not yet declared (e.g. CLOCK → FF clock pin)
  // must appear as an input port.
  for (const gate of Object.values(circuit.gates)) {
    if (EXCLUDE_FROM_VERILOG.has(gate.typeId) || !gateRegistry.has(gate.typeId)) continue;
    const def = gateRegistry.get(gate.typeId);
    for (const inp of def.inputs) {
      const wName = byPort[`${gate.id}:${inp.id}`];
      if (wName && !inputs.includes(wName) && !outputs.includes(wName) && !wires.has(wName) && !regs.has(wName)) {
        inputs.push(wName);
      }
    }
  }

  // Bug fix 2: due to non-deterministic gate iteration order, a signal may have
  // been added to regs or wires before its OUTPUT_LED was processed.
  // Remove any duplicate declarations — the port list already covers these signals.
  for (const name of outputs) { regs.delete(name); wires.delete(name); }

  // Build port declarations without trailing comma issues
  const portParts: string[] = [];
  for (const name of inputs)  portParts.push(`  input  wire ${name}`);
  for (const name of outputs) portParts.push(`  output reg  ${name}`);

  const lines: string[] = [
    `// Generated by LogicSim`,
    `// ${new Date().toISOString()}`,
    ``,
    `module ${moduleName} (`,
    ...(portParts.length > 0
      ? [portParts.join(',\n'), `);`]
      : [`);`]
    ),
    ``,
    ...(wires.size > 0 ? [`  wire ${[...wires].join(', ')};`, ``] : []),
    ...(regs.size  > 0 ? [`  reg  ${[...regs].join(', ')};`,  ``] : []),
    ...(gateLines.length > 0 ? [...gateLines, ``] : []),
    ...(ffLines.length > 0 ? [
      `  // Sequential logic`,
      ...ffLines,
      ``,
    ] : []),
    `endmodule // ${moduleName}`,
  ];

  return lines.join('\n');
}

function defaultGateVerilog(gate: GateInstance, byPort: Record<string, string>): string {
  const def  = gateRegistry.get(gate.typeId);
  const ins  = def.inputs.map((p)  => byPort[`${gate.id}:${p.id}`] ?? `1'b0`);
  const outs = def.outputs.map((p) => byPort[`${gate.id}:${p.id}`] ?? `w_${sanitize(gate.id)}_${p.id}`);

  // Map type to Verilog primitive keyword
  const PRIM_MAP: Record<string, string> = {
    AND: 'and', OR: 'or', NOT: 'not', NAND: 'nand', NOR: 'nor',
    XOR: 'xor', XNOR: 'xnor', BUFFER: 'buf',
    AND3: 'and', AND4: 'and', OR3: 'or', OR4: 'or',
    NAND3: 'nand', NAND4: 'nand', NOR3: 'nor', NOR4: 'nor', XOR3: 'xor',
  };
  const prim = PRIM_MAP[gate.typeId];
  if (prim) {
    return `${prim} g_${sanitize(gate.id)}(${[...outs, ...ins].join(', ')});`;
  }

  return `// ${gate.typeId} (${gate.id}): manual Verilog implementation required`;
}
