import type { Circuit, GateInstance } from '../types';
import { gateRegistry } from '../registry/GateRegistry';

interface WireMap {
  /** portKey "gateId:portId" → signal name */
  byPort: Record<string, string>;
}

function sanitize(id: string) {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

function buildWireMap(circuit: Circuit): WireMap {
  const byPort: Record<string, string> = {};

  // Assign names to INPUT_SWITCH outputs
  let swIdx = 0;
  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      const name = gate.label ? sanitize(gate.label) : `sw_${swIdx++}`;
      byPort[`${gate.id}:out`] = name;
    }
  }

  // Assign names to all wires
  let wIdx = 0;
  for (const wire of Object.values(circuit.wires)) {
    const fromKey = `${wire.from.gateId}:${wire.from.portId}`;
    if (!byPort[fromKey]) {
      byPort[fromKey] = `w_${wIdx++}`;
    }
    byPort[`${wire.to.gateId}:${wire.to.portId}`] = byPort[fromKey];
  }

  // Assign names to OUTPUT_LED inputs
  let ledIdx = 0;
  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'OUTPUT_LED') {
      const inKey = `${gate.id}:in`;
      if (!byPort[inKey]) {
        const name = gate.label ? sanitize(gate.label) : `led_${ledIdx++}`;
        byPort[inKey] = name;
      }
    }
  }

  return { byPort };
}

export function generateVerilog(circuit: Circuit): string {
  const moduleName = sanitize(circuit.name) || 'circuit';
  const { byPort } = buildWireMap(circuit);

  const inputs: string[] = [];
  const outputs: string[] = [];
  const wires = new Set<string>();
  const gateLines: string[] = [];
  const ffLines: string[] = [];

  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      const name = byPort[`${gate.id}:out`] ?? `sw_${gate.id}`;
      inputs.push(name);
    } else if (gate.typeId === 'OUTPUT_LED') {
      const name = byPort[`${gate.id}:in`] ?? `led_${gate.id}`;
      outputs.push(name);
    } else if (gate.typeId !== 'TEXT_NOTE') {
      // Collect internal wire names
      const def = gateRegistry.get(gate.typeId);
      for (const out of def.outputs) {
        const k = `${gate.id}:${out.id}`;
        const wName = byPort[k];
        if (wName && !inputs.includes(wName) && !outputs.includes(wName)) {
          wires.add(wName);
        }
      }

      // Generate gate instantiation
      const def2 = gateRegistry.get(gate.typeId);
      if (def2.toVerilog) {
        const line = def2.toVerilog(gate, byPort);
        (gate.typeId.includes('FF') || gate.typeId.includes('REG') || gate.typeId.includes('LATCH') || gate.typeId.includes('SHIFT'))
          ? ffLines.push('  ' + line)
          : gateLines.push('  ' + line);
      } else {
        gateLines.push('  ' + defaultGateVerilog(gate, byPort));
      }
    }
  }

  const lines: string[] = [
    `// Generated by LogicSim`,
    `// ${new Date().toISOString()}`,
    ``,
    `module ${moduleName} (`,
    ...(inputs.length > 0 ? [`  input wire ${inputs.join(',\n  input wire ')},`] : []),
    ...(outputs.length > 0 ? [`  output reg ${outputs.join(',\n  output reg ')}`] : []),
    `);`,
    ``,
    ...(wires.size > 0 ? [`  wire ${[...wires].join(', ')};`, ``] : []),
    ...(gateLines.length > 0 ? [...gateLines, ``] : []),
    ...(ffLines.length > 0 ? [
      `  // Sequential logic`,
      ...ffLines,
      ``,
    ] : []),
    `endmodule // ${moduleName}`,
  ];

  return lines.join('\n');
}

function defaultGateVerilog(gate: GateInstance, byPort: Record<string, string>): string {
  const def = gateRegistry.get(gate.typeId);
  const ins = def.inputs.map((p) => byPort[`${gate.id}:${p.id}`] ?? `1'b0`);
  const outs = def.outputs.map((p) => byPort[`${gate.id}:${p.id}`] ?? `w_${gate.id}_${p.id}`);
  const prim = gate.typeId.toLowerCase().split('_')[0].replace(/\d/g, '');
  return `${prim} g_${sanitize(gate.id)}(${[...outs, ...ins].join(', ')});`;
}
