import type { Circuit, GateInstance } from '../types';
import { gateRegistry } from '../registry/GateRegistry';

function sanitize(id: string) {
  return id.replace(/[^a-zA-Z0-9_]/g, '_');
}

// Gate types that have no direct VHDL equivalent and should be excluded from logic
const EXCLUDE_FROM_VHDL = new Set([
  'CLOCK', 'PUSH_BTN', 'JUNCTION', 'TEXT_NOTE',
  'OUTPUT_LED_7SEG', 'DOT_MATRIX', 'STEPPER_MOTOR', 'ADC8',
  'ROM256', 'RAM256', 'CUSTOM_IC',
]);

function buildPortMap(circuit: Circuit) {
  const byPort: Record<string, string> = {};
  let swIdx = 0, wIdx = 0, ledIdx = 0;

  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      byPort[`${gate.id}:out`] = gate.label ? sanitize(gate.label) : `sw_${swIdx++}`;
    }
  }
  for (const wire of Object.values(circuit.wires)) {
    const fromKey = `${wire.from.gateId}:${wire.from.portId}`;
    if (!byPort[fromKey]) byPort[fromKey] = `w_${wIdx++}`;
    byPort[`${wire.to.gateId}:${wire.to.portId}`] = byPort[fromKey];
  }
  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'OUTPUT_LED') {
      const k = `${gate.id}:in`;
      if (!byPort[k]) byPort[k] = gate.label ? sanitize(gate.label) : `led_${ledIdx++}`;
    }
  }
  return byPort;
}

const VHDL_PRIM: Record<string, string> = {
  AND: 'and', OR: 'or', NOT: 'not', NAND: 'nand', NOR: 'nor',
  XOR: 'xor', XNOR: 'xnor',
  AND3: 'and', AND4: 'and', OR3: 'or', OR4: 'or',
  NAND3: 'nand', NAND4: 'nand', NOR3: 'nor', NOR4: 'nor', XOR3: 'xor',
};

export function generateVHDL(circuit: Circuit): string {
  const entityName = sanitize(circuit.name) || 'circuit';
  const byPort = buildPortMap(circuit);

  const inputs: string[] = [];
  const outputs: string[] = [];
  const signals = new Set<string>();
  const logic: string[] = [];
  const ffLogic: string[] = [];

  for (const gate of Object.values(circuit.gates)) {
    if (gate.typeId === 'INPUT_SWITCH') {
      inputs.push(byPort[`${gate.id}:out`] ?? `sw_${gate.id}`);
    } else if (gate.typeId === 'OUTPUT_LED') {
      outputs.push(byPort[`${gate.id}:in`] ?? `led_${gate.id}`);
    } else if (!EXCLUDE_FROM_VHDL.has(gate.typeId) && gateRegistry.has(gate.typeId)) {
      const def = gateRegistry.get(gate.typeId);

      // Collect internal signal declarations
      for (const out of def.outputs) {
        const s = byPort[`${gate.id}:${out.id}`];
        if (s && !inputs.includes(s) && !outputs.includes(s)) signals.add(s);
      }

      // Generate VHDL for this gate
      let line: string;
      if (gate.typeId === 'CONST_HIGH') {
        const s = byPort[`${gate.id}:out`];
        line = s ? `${s} <= '1'; -- CONST_HIGH` : '-- CONST_HIGH (unconnected)';
      } else if (gate.typeId === 'CONST_LOW') {
        const s = byPort[`${gate.id}:out`];
        line = s ? `${s} <= '0'; -- CONST_LOW` : '-- CONST_LOW (unconnected)';
      } else if (def.toVHDL) {
        line = def.toVHDL(gate, byPort);
      } else {
        line = defaultGateVHDL(gate, byPort);
      }

      // Multi-line support: indent each line of the block
      const indented = line.split('\n').map(l => '  ' + l).join('\n');
      (def.isSynchronous ? ffLogic : logic).push(indented);
    }
  }

  const portLines: string[] = [
    ...inputs.map((n) => `    ${n} : in STD_LOGIC`),
    ...outputs.map((n) => `    ${n} : out STD_LOGIC`),
  ];

  const lines = [
    `-- Generated by LogicSim`,
    `-- ${new Date().toISOString()}`,
    ``,
    `library IEEE;`,
    `use IEEE.STD_LOGIC_1164.ALL;`,
    ``,
    `entity ${entityName} is`,
    ...(portLines.length > 0
      ? [`  Port (`, portLines.join(';\n'), `  );`]
      : [`  -- no ports`]
    ),
    `end ${entityName};`,
    ``,
    `architecture Behavioral of ${entityName} is`,
    ...(signals.size > 0
      ? [...signals].map((s) => `  signal ${s} : STD_LOGIC := '0';`)
      : ['  -- no internal signals']),
    `begin`,
    ``,
    ...(logic.length > 0 ? [...logic, ``] : []),
    ...(ffLogic.length > 0 ? [
      `  -- Sequential / registered logic`,
      ...ffLogic,
      ``,
    ] : []),
    `end Behavioral;`,
  ];

  return lines.join('\n');
}

function defaultGateVHDL(gate: GateInstance, byPort: Record<string, string>): string {
  const def = gateRegistry.get(gate.typeId);
  const prim = VHDL_PRIM[gate.typeId];
  const outs = def.outputs.map((p) => byPort[`${gate.id}:${p.id}`] ?? `w_${gate.id}_${p.id}`);
  const ins  = def.inputs.map((p)  => byPort[`${gate.id}:${p.id}`] ?? `'0'`);

  if (!prim) {
    return `-- ${gate.typeId} (${gate.id}): manual VHDL implementation required`;
  }

  if (gate.typeId === 'NOT') {
    return `${outs[0]} <= not ${ins[0]}; -- ${gate.id}`;
  }
  if (gate.typeId === 'BUFFER') {
    return `${outs[0]} <= ${ins[0]}; -- BUFFER ${gate.id}`;
  }

  return `${outs[0]} <= ${ins.join(` ${prim} `)}; -- ${gate.id}`;
}
