// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_c1_basic_gates (
  input  wire a,
  input  wire b,
  input  wire c,
  output wire w_2
);

  wire w_0, w_1;

  and g_and1(w_0, a, b);
  or g_or1(w_1, w_0, c);
  not g_not1(w_2, w_1);

endmodule // gc_c1_basic_gates
`default_nettype wire
