// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_c3_sr_latch (
  input  wire s,
  input  wire r,
  output wire w_0,
  output wire w_1
);

  // SR-Latch dut (cross-coupled NOR)
  /* verilator lint_off UNOPTFLAT */
  nor g_dut_q (w_0,  r, w_1);
  nor g_dut_qn(w_1, s, w_0);
  /* verilator lint_on UNOPTFLAT */

endmodule // gc_c3_sr_latch
`default_nettype wire
