-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_c2_half_adder is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_c2_half_adder;

architecture Behavioral of gc_c2_half_adder is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  w_0_q <= a xor b; -- xor1
  w_1_q <= a and b; -- and1

  w_0 <= w_0_q;
  w_1 <= w_1_q;

end Behavioral;
