-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_c1_basic_gates is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    c : in STD_LOGIC;
    w_2 : out STD_LOGIC
  );
end gc_c1_basic_gates;

architecture Behavioral of gc_c1_basic_gates is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
begin

  w_0 <= a and b; -- and1
  w_1 <= w_0 or c; -- or1
  w_2_q <= not w_1; -- not1

  w_2 <= w_2_q;

end Behavioral;
