-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_m2_283_adder is
  Port (
    a1 : in STD_LOGIC;
    a2 : in STD_LOGIC;
    a3 : in STD_LOGIC;
    a4 : in STD_LOGIC;
    b1 : in STD_LOGIC;
    b2 : in STD_LOGIC;
    b3 : in STD_LOGIC;
    b4 : in STD_LOGIC;
    c0 : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC
  );
end gc_m2_283_adder;

architecture Behavioral of gc_m2_283_adder is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
begin

  -- 74HC283 dut
  process(a1,b1,a2,b2,a3,b3,a4,b4,c0)
    variable a_v : integer range 0 to 15;
    variable b_v : integer range 0 to 15;
    variable cin_v : integer range 0 to 1;
    variable sum_v : unsigned(4 downto 0);
  begin
    a_v := 0;
    if a1 = '1' then a_v := a_v + 1; end if;
    if a2 = '1' then a_v := a_v + 2; end if;
    if a3 = '1' then a_v := a_v + 4; end if;
    if a4 = '1' then a_v := a_v + 8; end if;
    b_v := 0;
    if b1 = '1' then b_v := b_v + 1; end if;
    if b2 = '1' then b_v := b_v + 2; end if;
    if b3 = '1' then b_v := b_v + 4; end if;
    if b4 = '1' then b_v := b_v + 8; end if;
    cin_v := 0;
    if c0 = '1' then cin_v := 1; end if;
    sum_v := to_unsigned(a_v + b_v + cin_v, 5);
    w_0_q <= std_logic(sum_v(0));
    w_1_q <= std_logic(sum_v(1));
    w_2_q <= std_logic(sum_v(2));
    w_3_q <= std_logic(sum_v(3));
    w_4_q <= std_logic(sum_v(4));
  end process; -- 74HC283 dut

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;

end Behavioral;
