-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_m1_dff_chain is
  Port (
    d : in STD_LOGIC;
    clk : in STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_m1_dff_chain;

architecture Behavioral of gc_m1_dff_chain is
  signal w_0 : STD_LOGIC := '0';
  signal w_dff1_q_n : STD_LOGIC := '0';
  signal w_dff2_q_n : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  w_1 <= w_1_q;

  -- Sequential / registered logic
  process(clk)
  begin
    if rising_edge(clk) then
      w_0 <= d;
    end if;
  end process; -- D-FF dff1
  w_dff1_q_n <= not w_0;
  process(clk)
  begin
    if rising_edge(clk) then
      w_1_q <= w_0;
    end if;
  end process; -- D-FF dff2
  w_dff2_q_n <= not w_1_q;

end Behavioral;
