// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_m1_dff_chain (
  input  wire d,
  input  wire clk,
  output reg  w_1
);

  wire w_dff1_q_n, w_dff2_q_n;
  reg  w_0;

  // Sequential logic
  always @(posedge clk) begin
    w_0 <= d;
  end // D-FF dff1
  assign w_dff1_q_n = ~w_0;
  always @(posedge clk) begin
    w_1 <= w_0;
  end // D-FF dff2
  assign w_dff2_q_n = ~w_1;

endmodule // gc_m1_dff_chain
`default_nettype wire
