// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_m3_counter_gate (
  input  wire clk,
  input  wire clrn,
  input  wire ldn,
  input  wire enp,
  input  wire ent,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  output wire w_2
);

  wire w_0, w_1, w_ctr_q2, w_ctr_q3, w_ctr_rco;

  reg [3:0] cnt_ctr;

  and g_and1(w_2, w_0, w_1);

  // Sequential logic
  // 74HC161 ctr
  always @(posedge clk or negedge clrn) begin
    if      (!clrn)               cnt_ctr <= 4'd0;
    else if (!ldn)                cnt_ctr <= {d3,d2,d1,d0};
    else if (enp && ent)       cnt_ctr <= cnt_ctr + 1'b1;
  end // 74HC161 ctr
  assign w_0 = cnt_ctr[0];
  assign w_1 = cnt_ctr[1];
  assign w_ctr_q2 = cnt_ctr[2];
  assign w_ctr_q3 = cnt_ctr[3];
  assign w_ctr_rco  = ent & (cnt_ctr == 4'd15);

endmodule // gc_m3_counter_gate
`default_nettype wire