// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_m2_283_adder (
  input  wire a1,
  input  wire a2,
  input  wire a3,
  input  wire a4,
  input  wire b1,
  input  wire b2,
  input  wire b3,
  input  wire b4,
  input  wire c0,
  output wire w_0,
  output wire w_1,
  output wire w_2,
  output wire w_3,
  output wire w_4
);

  // 74HC283 dut
  wire [4:0] sum_dut = {1'b0,a4,a3,a2,a1} + {1'b0,b4,b3,b2,b1} + {4'b0,c0};
  assign w_0 = sum_dut[0];
  assign w_1 = sum_dut[1];
  assign w_2 = sum_dut[2];
  assign w_3 = sum_dut[3];
  assign w_4 = sum_dut[4];

endmodule // gc_m2_283_adder
`default_nettype wire
