-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s1_dff_assr is
  Port (
    d : in STD_LOGIC;
    clk : in STD_LOGIC;
    s : in STD_LOGIC;
    r : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end gc_s1_dff_assr;

architecture Behavioral of gc_s1_dff_assr is
  signal w_dut_q_n : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;

  -- Sequential / registered logic
  process(clk, r, s)
  begin
    if    r = '1'           then w_0_q <= '0';
    elsif s = '1'           then w_0_q <= '1';
    elsif rising_edge(clk) then
      w_0_q <= d;
    end if;
  end process; -- D-FF/ASSR dut
  w_dut_q_n <= not w_0_q;

end Behavioral;