-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s2_jkff_toggle is
  Port (
    j : in STD_LOGIC;
    k : in STD_LOGIC;
    clk : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end gc_s2_jkff_toggle;

architecture Behavioral of gc_s2_jkff_toggle is
  signal w_dut_q_n : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;

  -- Sequential / registered logic
  process(clk)
  begin
    if rising_edge(clk) then
      if    j = '1' and k = '0' then w_0_q <= '1';
      elsif j = '0' and k = '1' then w_0_q <= '0';
      elsif j = '1' and k = '1' then w_0_q <= not w_0_q;
      end if;
    end if;
  end process; -- JK-FF dut
  w_dut_q_n <= not w_0_q;

end Behavioral;
