-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s5_dff_basic is
  Port (
    d : in STD_LOGIC;
    clk : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_s5_dff_basic;

architecture Behavioral of gc_s5_dff_basic is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;

  -- Sequential / registered logic
  process(clk)
  begin
    if rising_edge(clk) then
      w_0_q <= d;
    end if;
  end process; -- D-FF dut
  w_1_q <= not w_0_q;

end Behavioral;