// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_s5_dff_basic (
  input  wire d,
  input  wire clk,
  output reg  w_0,
  output wire w_1
);

  // Sequential logic
  always @(posedge clk) begin
    w_0 <= d;
  end // D-FF dut
  assign w_1 = ~w_0;

endmodule // gc_s5_dff_basic
`default_nettype wire