// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_s1_dff_assr (
  input  wire d,
  input  wire clk,
  input  wire s,
  input  wire r,
  output reg  w_0
);

  wire w_dut_q_n;

  // Sequential logic
  always @(posedge clk or posedge r or posedge s) begin
    if      (r)  w_0 <= 1'b0;
    else if (s)  w_0 <= 1'b1;
    else begin
      w_0 <= d;
    end
  end // D-FF/ASSR dut
  assign w_dut_q_n = ~w_0;

endmodule // gc_s1_dff_assr
`default_nettype wire
