// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_s3_74hc74 (
  input  wire pre1,
  input  wire clr1,
  input  wire d1,
  input  wire clk1,
  input  wire pre2,
  input  wire clr2,
  input  wire d2,
  input  wire clk2,
  output reg  w_0,
  output reg  w_1
);

  wire w_dut_qn1, w_dut_qn2;

  // Sequential logic
  // 74HC74 dut
  always @(posedge clk1 or negedge pre1 or negedge clr1) begin
    if      (!pre1) w_0 <= 1'b1;
    else if (!clr1) w_0 <= 1'b0;
    else               w_0 <= d1;
  end
  always @(posedge clk2 or negedge pre2 or negedge clr2) begin
    if      (!pre2) w_1 <= 1'b1;
    else if (!clr2) w_1 <= 1'b0;
    else               w_1 <= d2;
  end // 74HC74 dut
  assign w_dut_qn1 = ~w_0;
  assign w_dut_qn2 = ~w_1;

endmodule // gc_s3_74hc74
`default_nettype wire