-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s4_reg4_enable is
  Port (
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    en : in STD_LOGIC;
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC
  );
end gc_s4_reg4_enable;

architecture Behavioral of gc_s4_reg4_enable is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;

  -- Sequential / registered logic
  -- REG4 dut
  process(clk, rst)
  begin
    if rst = '1' then
      w_0_q <= '0'; w_1_q <= '0'; w_2_q <= '0'; w_3_q <= '0';
    elsif rising_edge(clk) then
      if en = '1' then
        w_0_q <= d0; w_1_q <= d1; w_2_q <= d2; w_3_q <= d3;
      end if;
    end if;
  end process; -- REG4 dut

end Behavioral;
