-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_s3_74hc74 is
  Port (
    pre1 : in STD_LOGIC;
    clr1 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    clk1 : in STD_LOGIC;
    pre2 : in STD_LOGIC;
    clr2 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    clk2 : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_s3_74hc74;

architecture Behavioral of gc_s3_74hc74 is
  signal w_dut_qn1 : STD_LOGIC := '0';
  signal w_dut_qn2 : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;

  -- Sequential / registered logic
  -- 74HC74 dut
  process(clk1, pre1, clr1)
  begin
    if    pre1 = '0' then w_0_q <= '1';
    elsif clr1 = '0' then w_0_q <= '0';
    elsif rising_edge(clk1) then w_0_q <= d1;
    end if;
  end process;
  process(clk2, pre2, clr2)
  begin
    if    pre2 = '0' then w_1_q <= '1';
    elsif clr2 = '0' then w_1_q <= '0';
    elsif rising_edge(clk2) then w_1_q <= d2;
    end if;
  end process; -- 74HC74 dut
  w_dut_qn1 <= not w_0_q;
  w_dut_qn2 <= not w_1_q;

end Behavioral;