// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_s4_reg4_enable (
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  input  wire en,
  input  wire clk,
  input  wire rst,
  output reg  w_0,
  output reg  w_1,
  output reg  w_2,
  output reg  w_3
);

  // Sequential logic
  // REG4 dut
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_0 <= 1'b0; w_1 <= 1'b0; w_2 <= 1'b0; w_3 <= 1'b0;
    end else if (en) begin
      w_0 <= d0; w_1 <= d1; w_2 <= d2; w_3 <= d3;
    end
  end // REG4 dut

endmodule // gc_s4_reg4_enable
`default_nettype wire