-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_t2_bus_mux is
  Port (
    a1 : in STD_LOGIC;
    oe1 : in STD_LOGIC;
    a2 : in STD_LOGIC;
    oe2 : in STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end gc_t2_bus_mux;

architecture Behavioral of gc_t2_bus_mux is
  signal w_0 : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  -- TRIBUF buf1
  w_0 <= a1 when oe1 = '0' else 'Z';
  -- TRIBUF buf2
  w_1_q <= a2 when oe2 = '0' else 'Z';

  w_1 <= w_1_q;

end Behavioral;
