// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_t2_bus_mux (
  input  wire a1,
  input  wire oe1,
  input  wire a2,
  input  wire oe2,
  output wire w_1
);

  wire w_0;

  // TRIBUF buf1
  assign w_0 = (~oe1) ? a1 : 1'bz;
  // TRIBUF buf2
  assign w_1 = (~oe2) ? a2 : 1'bz;

endmodule // gc_t2_bus_mux
`default_nettype wire