// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_t1_tribuf_direct (
  input  wire a,
  input  wire oe,
  output wire w_0
);

  // TRIBUF dut
  assign w_0 = (~oe) ? a : 1'bz;

endmodule // gc_t1_tribuf_direct
`default_nettype wire
