-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_12_nested_halfadder_parent is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC
  );
end gc_v2_12_nested_halfadder_parent;

architecture Behavioral of gc_v2_12_nested_halfadder_parent is
  signal w_3 : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
begin

  w_3 <= a xor b; -- parent_flat_ha0_flat_xor1
  w_4 <= a and b; -- parent_flat_ha0_flat_and1
  w_0_q <= w_3 or w_4; -- parent_flat_or_any
  w_1_q <= a or b; -- raw_or
  w_2_q <= w_0_q xor w_1_q; -- xor_diff

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;

end Behavioral;