// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_6_custom_halfadder (
  input  wire a,
  input  wire b,
  input  wire cin,
  output wire w_6,
  output wire w_8,
  output wire w_7,
  output wire w_9,
  output wire w_10,
  output wire w_11
);

  wire w_0, w_1, w_2, w_3, w_4, w_5;

  xor g_ha0__xor1(w_0, a, b);
  and g_ha0__and1(w_1, a, b);
  xor g_ha1__xor1(w_6, w_0, cin);
  and g_ha1__and1(w_2, w_0, cin);
  or g_or_custom(w_8, w_1, w_2);
  xor g_raw_xor_ab(w_3, a, b);
  xor g_raw_sum(w_7, w_3, cin);
  and g_raw_and_ab(w_4, a, b);
  and g_raw_and_cin(w_5, w_3, cin);
  or g_raw_or(w_9, w_4, w_5);
  xor g_xor_sum_diff(w_10, w_6, w_7);
  xor g_xor_cout_diff(w_11, w_8, w_9);

endmodule // gc_v2_6_custom_halfadder
`default_nettype wire