-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_8_sequential_feedback is
  Port (
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    en : in STD_LOGIC;
    d : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_3 : out STD_LOGIC
  );
end gc_v2_8_sequential_feedback;

architecture Behavioral of gc_v2_8_sequential_feedback is
  signal w_4 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_6 : STD_LOGIC := '0';
  signal w_ff1_q_n : STD_LOGIC := '0';
  signal w_ff2_q_n : STD_LOGIC := '0';
  signal w_ff3_q_n : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  w_4 <= w_0_q when en = '1' else d; -- MUX2 g_mux1
  w_5 <= w_1_q when en = '1' else d2; -- MUX2 g_mux2
  w_3_q <= w_2_q xor w_0_q; -- g_xor_fb
  w_6 <= w_3_q when en = '1' else d3; -- MUX2 g_mux3

  w_3 <= w_3_q;
  w_2 <= w_2_q;
  w_0 <= w_0_q;
  w_1 <= w_1_q;

  -- Sequential / registered logic
  process(clk, rst)
  begin
    if rst = '1' then
      w_2_q <= '0';
    elsif rising_edge(clk) then
      w_2_q <= w_4;
    end if;
  end process; -- D-FF/R ff1
  w_ff1_q_n <= not w_2_q;
  process(clk, rst)
  begin
    if rst = '1' then
      w_0_q <= '0';
    elsif rising_edge(clk) then
      w_0_q <= w_5;
    end if;
  end process; -- D-FF/R ff2
  w_ff2_q_n <= not w_0_q;
  process(clk, rst)
  begin
    if rst = '1' then
      w_1_q <= '0';
    elsif rising_edge(clk) then
      w_1_q <= w_6;
    end if;
  end process; -- D-FF/R ff3
  w_ff3_q_n <= not w_1_q;

end Behavioral;