-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_6_custom_halfadder is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    cin : in STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_8 : out STD_LOGIC;
    w_7 : out STD_LOGIC;
    w_9 : out STD_LOGIC;
    w_10 : out STD_LOGIC;
    w_11 : out STD_LOGIC
  );
end gc_v2_6_custom_halfadder;

architecture Behavioral of gc_v2_6_custom_halfadder is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_2 : STD_LOGIC := '0';
  signal w_3 : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  signal w_9_q : STD_LOGIC := '0';
  signal w_10_q : STD_LOGIC := '0';
  signal w_11_q : STD_LOGIC := '0';
begin

  w_0 <= a xor b; -- ha0__xor1
  w_1 <= a and b; -- ha0__and1
  w_6_q <= w_0 xor cin; -- ha1__xor1
  w_2 <= w_0 and cin; -- ha1__and1
  w_8_q <= w_1 or w_2; -- or_custom
  w_3 <= a xor b; -- raw_xor_ab
  w_7_q <= w_3 xor cin; -- raw_sum
  w_4 <= a and b; -- raw_and_ab
  w_5 <= w_3 and cin; -- raw_and_cin
  w_9_q <= w_4 or w_5; -- raw_or
  w_10_q <= w_6_q xor w_7_q; -- xor_sum_diff
  w_11_q <= w_8_q xor w_9_q; -- xor_cout_diff

  w_6 <= w_6_q;
  w_8 <= w_8_q;
  w_7 <= w_7_q;
  w_9 <= w_9_q;
  w_10 <= w_10_q;
  w_11 <= w_11_q;

end Behavioral;