-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_11_custom_hc194_wrap is
  Port (
    clk : in STD_LOGIC;
    clrn : in STD_LOGIC;
    s0 : in STD_LOGIC;
    s1 : in STD_LOGIC;
    sr : in STD_LOGIC;
    sl : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC
  );
end gc_v2_11_custom_hc194_wrap;

architecture Behavioral of gc_v2_11_custom_hc194_wrap is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal reg_wrap_flat_dut : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;

  -- Sequential / registered logic
  -- 74HC194 wrap_flat_dut
  process(clk, clrn)
  begin
    if clrn = '0' then reg_wrap_flat_dut <= (others => '0');
    elsif rising_edge(clk) then
      case STD_LOGIC_VECTOR'(s1 & s0) is
        when "01" => reg_wrap_flat_dut <= sr & reg_wrap_flat_dut(3 downto 1);
        when "10" => reg_wrap_flat_dut <= reg_wrap_flat_dut(2 downto 0) & sl;
        when "11" => reg_wrap_flat_dut <= d3 & d2 & d1 & d0;
        when others => null;
      end case;
    end if;
  end process; -- 74HC194 wrap_flat_dut
  w_0_q <= reg_wrap_flat_dut(0);
  w_1_q <= reg_wrap_flat_dut(1);
  w_2_q <= reg_wrap_flat_dut(2);
  w_3_q <= reg_wrap_flat_dut(3);

end Behavioral;