// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_9_custom_reg4_pipeline (
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  input  wire en,
  input  wire clk,
  input  wire rst,
  output reg  w_0,
  output reg  w_1,
  output reg  w_2,
  output reg  w_3,
  output reg  w_4,
  output reg  w_5,
  output reg  w_6,
  output reg  w_7,
  output wire w_8
);

  xor g_cmp_xor(w_8, w_0, w_4);

  // Sequential logic
  // REG4 reg_a__dut
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_0 <= 1'b0; w_1 <= 1'b0; w_2 <= 1'b0; w_3 <= 1'b0;
    end else if (en) begin
      w_0 <= d0; w_1 <= d1; w_2 <= d2; w_3 <= d3;
    end
  end // REG4 reg_a__dut
  // REG4 reg_b__dut
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_4 <= 1'b0; w_5 <= 1'b0; w_6 <= 1'b0; w_7 <= 1'b0;
    end else if (en) begin
      w_4 <= w_0; w_5 <= w_1; w_6 <= w_2; w_7 <= w_3;
    end
  end // REG4 reg_b__dut

endmodule // gc_v2_9_custom_reg4_pipeline
`default_nettype wire