-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_15_ram_decode_capture_bus is
  Port (
    a0 : in STD_LOGIC;
    a1 : in STD_LOGIC;
    a2 : in STD_LOGIC;
    g1 : in STD_LOGIC;
    di0 : in STD_LOGIC;
    di1 : in STD_LOGIC;
    di2 : in STD_LOGIC;
    di3 : in STD_LOGIC;
    di4 : in STD_LOGIC;
    di5 : in STD_LOGIC;
    di6 : in STD_LOGIC;
    di7 : in STD_LOGIC;
    we : in STD_LOGIC;
    cs : in STD_LOGIC;
    oe : in STD_LOGIC;
    le373 : in STD_LOGIC;
    oe373 : in STD_LOGIC;
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    w_13 : out STD_LOGIC;
    w_14 : out STD_LOGIC;
    w_15 : out STD_LOGIC;
    w_16 : out STD_LOGIC;
    w_17 : out STD_LOGIC;
    w_18 : out STD_LOGIC;
    w_2 : out STD_LOGIC
  );
end gc_v2_15_ram_decode_capture_bus;

architecture Behavioral of gc_v2_15_ram_decode_capture_bus is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_3 : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_6 : STD_LOGIC := '0';
  signal w_7 : STD_LOGIC := '0';
  signal w_8 : STD_LOGIC := '0';
  signal w_9 : STD_LOGIC := '0';
  signal w_11 : STD_LOGIC := '0';
  signal w_dec_y1 : STD_LOGIC := '0';
  signal w_dec_y2 : STD_LOGIC := '0';
  signal w_dec_y3 : STD_LOGIC := '0';
  signal w_dec_y4 : STD_LOGIC := '0';
  signal w_12 : STD_LOGIC := '0';
  signal w_dec_y6 : STD_LOGIC := '0';
  signal w_dec_y7 : STD_LOGIC := '0';
  signal w_10 : STD_LOGIC := '0';
  signal w_mux_yn : STD_LOGIC := '0';
  signal w_lat373_q1 : STD_LOGIC := '0';
  signal w_lat373_q2 : STD_LOGIC := '0';
  signal w_lat373_q3 : STD_LOGIC := '0';
  signal w_lat373_q4 : STD_LOGIC := '0';
  signal w_lat373_q6 : STD_LOGIC := '0';
  signal w_lat373_q7 : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_13_q : STD_LOGIC := '0';
  signal w_14_q : STD_LOGIC := '0';
  signal w_15_q : STD_LOGIC := '0';
  signal w_16_q : STD_LOGIC := '0';
  signal w_17_q : STD_LOGIC := '0';
  signal w_18_q : STD_LOGIC := '0';
  type t_ram_ram is array (0 to 255) of STD_LOGIC_VECTOR(7 downto 0);
  signal ram_ram : t_ram_ram := (others => (others => '0'));
  signal latch_lat373 : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_0 <= '0'; -- CONST_LOW
  w_1 <= '1'; -- CONST_HIGH
  -- RAM256 ram
  process(a0, a1, a2, w_0, w_0, w_0, w_0, w_0, di0, di1, di2, di3, di4, di5, di6, di7, we, cs) -- async write (transparent latch)
  begin
    if cs = '0' and we = '0' then
      ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0)))) <= std_logic_vector'(di7 & di6 & di5 & di4 & di3 & di2 & di1 & di0);
    end if;
  end process;
  process(a0, a1, a2, w_0, w_0, w_0, w_0, w_0, oe, cs, ram_ram) -- read
  begin
    w_2_q <= 'Z'; w_3 <= 'Z'; w_4 <= 'Z'; w_5 <= 'Z'; w_6 <= 'Z'; w_7 <= 'Z'; w_8 <= 'Z'; w_9 <= 'Z';
    if cs = '0' and oe = '0' then
      w_2_q <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(0);
      w_3 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(1);
      w_4 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(2);
      w_5 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(3);
      w_6 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(4);
      w_7 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(5);
      w_8 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(6);
      w_9 <= ram_ram(to_integer(unsigned(std_logic_vector'(w_0 & w_0 & w_0 & w_0 & w_0 & a2 & a1 & a0))))(7);
    end if;
  end process; -- RAM256 ram
  -- 74HC138 dec
  w_11 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "000" else '1';
  w_dec_y1 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "001" else '1';
  w_dec_y2 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "010" else '1';
  w_dec_y3 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "011" else '1';
  w_dec_y4 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "100" else '1';
  w_12 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "101" else '1';
  w_dec_y6 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "110" else '1';
  w_dec_y7 <= '0' when (g1 = '1' and w_0 = '0' and w_0 = '0') and STD_LOGIC_VECTOR'(a2 & a1 & a0) = "111" else '1';
  -- 74HC151 mux
  w_10 <= '0' when w_0 = '1' else
         w_2_q when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("000") else
         w_3 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("001") else
         w_4 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("010") else
         w_5 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("011") else
         w_6 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("100") else
         w_7 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("101") else
         w_8 when STD_LOGIC_VECTOR'(a2 & a1 & a0) = STD_LOGIC_VECTOR'("110") else
         w_9;
  w_mux_yn <= not w_10;

  w_2 <= w_2_q;
  w_13 <= w_13_q;
  w_14 <= w_14_q;
  w_15 <= w_15_q;
  w_16 <= w_16_q;
  w_17 <= w_17_q;
  w_18 <= w_18_q;

  -- Sequential / registered logic
  -- 74HC373 lat373
  process(le373, w_2_q, w_3, w_4, w_5, w_6, w_7, w_8, w_9)
  begin
    if le373 = '1' then
      latch_lat373 <= w_9 & w_8 & w_7 & w_6 & w_5 & w_4 & w_3 & w_2_q;
    end if;
  end process; -- 74HC373 lat373
  w_13_q <= 'Z' when oe373 = '1' else latch_lat373(0);
  w_lat373_q1 <= 'Z' when oe373 = '1' else latch_lat373(1);
  w_lat373_q2 <= 'Z' when oe373 = '1' else latch_lat373(2);
  w_lat373_q3 <= 'Z' when oe373 = '1' else latch_lat373(3);
  w_lat373_q4 <= 'Z' when oe373 = '1' else latch_lat373(4);
  w_14_q <= 'Z' when oe373 = '1' else latch_lat373(5);
  w_lat373_q6 <= 'Z' when oe373 = '1' else latch_lat373(6);
  w_lat373_q7 <= 'Z' when oe373 = '1' else latch_lat373(7);
  -- REG4 reg
  process(clk, rst)
  begin
    if rst = '1' then
      w_15_q <= '0'; w_16_q <= '0'; w_17_q <= '0'; w_18_q <= '0';
    elsif rising_edge(clk) then
      if w_1 = '1' then
        w_15_q <= w_10; w_16_q <= w_11; w_17_q <= w_12; w_18_q <= w_2_q;
      end if;
    end if;
  end process; -- REG4 reg

end Behavioral;