-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_7_bus_conflict_system is
  Port (
    a_clk : in STD_LOGIC;
    a_oe : in STD_LOGIC;
    a_d0 : in STD_LOGIC;
    a_d1 : in STD_LOGIC;
    b_clk : in STD_LOGIC;
    b_oe : in STD_LOGIC;
    b_d0 : in STD_LOGIC;
    b_d1 : in STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_7 : out STD_LOGIC;
    w_10 : out STD_LOGIC;
    w_12 : out STD_LOGIC
  );
end gc_v2_7_bus_conflict_system;

architecture Behavioral of gc_v2_7_bus_conflict_system is
  signal w_1 : STD_LOGIC := '0';
  signal w_0 : STD_LOGIC := '0';
  signal w_2 : STD_LOGIC := '0';
  signal w_master_a_q1 : STD_LOGIC := '0';
  signal w_master_a_q2 : STD_LOGIC := '0';
  signal w_master_a_q3 : STD_LOGIC := '0';
  signal w_master_a_q4 : STD_LOGIC := '0';
  signal w_master_a_q5 : STD_LOGIC := '0';
  signal w_master_a_q6 : STD_LOGIC := '0';
  signal w_master_a_q7 : STD_LOGIC := '0';
  signal w_shadow_a_q2 : STD_LOGIC := '0';
  signal w_shadow_a_q3 : STD_LOGIC := '0';
  signal w_master_b_q1 : STD_LOGIC := '0';
  signal w_master_b_q2 : STD_LOGIC := '0';
  signal w_master_b_q3 : STD_LOGIC := '0';
  signal w_master_b_q4 : STD_LOGIC := '0';
  signal w_master_b_q5 : STD_LOGIC := '0';
  signal w_master_b_q6 : STD_LOGIC := '0';
  signal w_master_b_q7 : STD_LOGIC := '0';
  signal w_shadow_b_q2 : STD_LOGIC := '0';
  signal w_shadow_b_q3 : STD_LOGIC := '0';
  signal w_8 : STD_LOGIC := '0';
  signal w_9 : STD_LOGIC := '0';
  signal w_11 : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  signal w_10_q : STD_LOGIC := '0';
  signal w_12_q : STD_LOGIC := '0';
  signal reg_master_a : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
  signal reg_master_b : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_1 <= '1'; -- CONST_HIGH
  w_0 <= '0'; -- CONST_LOW
  w_8 <= not a_oe; -- not_a_oe
  w_9 <= not b_oe; -- not_b_oe
  w_10_q <= w_8 and w_9; -- oe_overlap_gate
  w_11 <= w_4_q xor w_6_q; -- bit0_diff
  w_12_q <= w_11 and w_10_q; -- conflict0_gate

  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_3 <= w_3_q;
  w_6 <= w_6_q;
  w_7 <= w_7_q;
  w_10 <= w_10_q;
  w_12 <= w_12_q;

  -- Sequential / registered logic
  -- 74HC374 master_a
  process(a_clk)
  begin
    if rising_edge(a_clk) then
      reg_master_a <= w_0 & w_0 & w_0 & w_0 & w_0 & w_0 & a_d1 & a_d0;
    end if;
  end process; -- 74HC374 master_a
  w_2 <= 'Z' when a_oe = '1' else reg_master_a(0);
  w_master_a_q1 <= 'Z' when a_oe = '1' else reg_master_a(1);
  w_master_a_q2 <= 'Z' when a_oe = '1' else reg_master_a(2);
  w_master_a_q3 <= 'Z' when a_oe = '1' else reg_master_a(3);
  w_master_a_q4 <= 'Z' when a_oe = '1' else reg_master_a(4);
  w_master_a_q5 <= 'Z' when a_oe = '1' else reg_master_a(5);
  w_master_a_q6 <= 'Z' when a_oe = '1' else reg_master_a(6);
  w_master_a_q7 <= 'Z' when a_oe = '1' else reg_master_a(7);
  -- REG4 shadow_a
  process(a_clk, w_0)
  begin
    if w_0 = '1' then
      w_4_q <= '0'; w_5_q <= '0'; w_shadow_a_q2 <= '0'; w_shadow_a_q3 <= '0';
    elsif rising_edge(a_clk) then
      if w_1 = '1' then
        w_4_q <= a_d0; w_5_q <= a_d1; w_shadow_a_q2 <= w_0; w_shadow_a_q3 <= w_0;
      end if;
    end if;
  end process; -- REG4 shadow_a
  -- 74HC374 master_b
  process(b_clk)
  begin
    if rising_edge(b_clk) then
      reg_master_b <= w_0 & w_0 & w_0 & w_0 & w_0 & w_0 & b_d1 & b_d0;
    end if;
  end process; -- 74HC374 master_b
  w_3_q <= 'Z' when b_oe = '1' else reg_master_b(0);
  w_master_b_q1 <= 'Z' when b_oe = '1' else reg_master_b(1);
  w_master_b_q2 <= 'Z' when b_oe = '1' else reg_master_b(2);
  w_master_b_q3 <= 'Z' when b_oe = '1' else reg_master_b(3);
  w_master_b_q4 <= 'Z' when b_oe = '1' else reg_master_b(4);
  w_master_b_q5 <= 'Z' when b_oe = '1' else reg_master_b(5);
  w_master_b_q6 <= 'Z' when b_oe = '1' else reg_master_b(6);
  w_master_b_q7 <= 'Z' when b_oe = '1' else reg_master_b(7);
  -- REG4 shadow_b
  process(b_clk, w_0)
  begin
    if w_0 = '1' then
      w_6_q <= '0'; w_7_q <= '0'; w_shadow_b_q2 <= '0'; w_shadow_b_q3 <= '0';
    elsif rising_edge(b_clk) then
      if w_1 = '1' then
        w_6_q <= b_d0; w_7_q <= b_d1; w_shadow_b_q2 <= w_0; w_shadow_b_q3 <= w_0;
      end if;
    end if;
  end process; -- REG4 shadow_b

end Behavioral;