-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_5_decode_tree is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    c : in STD_LOGIC;
    g1 : in STD_LOGIC;
    g2a : in STD_LOGIC;
    g2b : in STD_LOGIC;
    ein : in STD_LOGIC;
    le373 : in STD_LOGIC;
    oe373 : in STD_LOGIC;
    clk374 : in STD_LOGIC;
    oe374 : in STD_LOGIC;
    w_9 : out STD_LOGIC;
    w_10 : out STD_LOGIC;
    w_11 : out STD_LOGIC;
    w_12 : out STD_LOGIC;
    w_13 : out STD_LOGIC;
    w_14 : out STD_LOGIC;
    w_15 : out STD_LOGIC;
    w_16 : out STD_LOGIC;
    w_22 : out STD_LOGIC;
    w_23 : out STD_LOGIC;
    w_24 : out STD_LOGIC;
    w_25 : out STD_LOGIC;
    w_26 : out STD_LOGIC
  );
end gc_v2_5_decode_tree;

architecture Behavioral of gc_v2_5_decode_tree is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_2 : STD_LOGIC := '0';
  signal w_3 : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_6 : STD_LOGIC := '0';
  signal w_7 : STD_LOGIC := '0';
  signal w_8 : STD_LOGIC := '0';
  signal w_17 : STD_LOGIC := '0';
  signal w_18 : STD_LOGIC := '0';
  signal w_19 : STD_LOGIC := '0';
  signal w_20 : STD_LOGIC := '0';
  signal w_21 : STD_LOGIC := '0';
  signal w_reg374_q5 : STD_LOGIC := '0';
  signal w_reg374_q6 : STD_LOGIC := '0';
  signal w_reg374_q7 : STD_LOGIC := '0';
  signal w_9_q : STD_LOGIC := '0';
  signal w_10_q : STD_LOGIC := '0';
  signal w_11_q : STD_LOGIC := '0';
  signal w_12_q : STD_LOGIC := '0';
  signal w_13_q : STD_LOGIC := '0';
  signal w_14_q : STD_LOGIC := '0';
  signal w_15_q : STD_LOGIC := '0';
  signal w_16_q : STD_LOGIC := '0';
  signal w_22_q : STD_LOGIC := '0';
  signal w_23_q : STD_LOGIC := '0';
  signal w_24_q : STD_LOGIC := '0';
  signal w_25_q : STD_LOGIC := '0';
  signal w_26_q : STD_LOGIC := '0';
  signal latch_lat373 : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
  signal reg_reg374 : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_0 <= '0'; -- CONST_LOW
  -- 74HC138 dec138
  w_1 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "000" else '1';
  w_2 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "001" else '1';
  w_3 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "010" else '1';
  w_4 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "011" else '1';
  w_5 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "100" else '1';
  w_6 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "101" else '1';
  w_7 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "110" else '1';
  w_8 <= '0' when (g1 = '1' and g2a = '0' and g2b = '0') and STD_LOGIC_VECTOR'(c & b & a) = "111" else '1';
  -- 74HC148 enc148
  process(ein,w_1,w_2,w_3,w_4,w_5,w_6,w_7,w_8)
  begin
    if    ein = '1' then w_19<='1'; w_18<='1'; w_17<='1'; w_20<='1'; w_21<='1';
    elsif w_8  = '0' then w_19<='0'; w_18<='0'; w_17<='0'; w_20<='0'; w_21<='1';
    elsif w_7  = '0' then w_19<='0'; w_18<='0'; w_17<='1'; w_20<='0'; w_21<='1';
    elsif w_6  = '0' then w_19<='0'; w_18<='1'; w_17<='0'; w_20<='0'; w_21<='1';
    elsif w_5  = '0' then w_19<='0'; w_18<='1'; w_17<='1'; w_20<='0'; w_21<='1';
    elsif w_4  = '0' then w_19<='1'; w_18<='0'; w_17<='0'; w_20<='0'; w_21<='1';
    elsif w_3  = '0' then w_19<='1'; w_18<='0'; w_17<='1'; w_20<='0'; w_21<='1';
    elsif w_2  = '0' then w_19<='1'; w_18<='1'; w_17<='0'; w_20<='0'; w_21<='1';
    elsif w_1  = '0' then w_19<='1'; w_18<='1'; w_17<='1'; w_20<='0'; w_21<='1';
    else                    w_19<='1'; w_18<='1'; w_17<='1'; w_20<='1'; w_21<='0';
    end if;
  end process; -- 74HC148 enc148

  w_9 <= w_9_q;
  w_10 <= w_10_q;
  w_11 <= w_11_q;
  w_12 <= w_12_q;
  w_13 <= w_13_q;
  w_14 <= w_14_q;
  w_15 <= w_15_q;
  w_16 <= w_16_q;
  w_22 <= w_22_q;
  w_23 <= w_23_q;
  w_24 <= w_24_q;
  w_25 <= w_25_q;
  w_26 <= w_26_q;

  -- Sequential / registered logic
  -- 74HC373 lat373
  process(le373, w_1, w_2, w_3, w_4, w_5, w_6, w_7, w_8)
  begin
    if le373 = '1' then
      latch_lat373 <= w_8 & w_7 & w_6 & w_5 & w_4 & w_3 & w_2 & w_1;
    end if;
  end process; -- 74HC373 lat373
  w_9_q <= 'Z' when oe373 = '1' else latch_lat373(0);
  w_10_q <= 'Z' when oe373 = '1' else latch_lat373(1);
  w_11_q <= 'Z' when oe373 = '1' else latch_lat373(2);
  w_12_q <= 'Z' when oe373 = '1' else latch_lat373(3);
  w_13_q <= 'Z' when oe373 = '1' else latch_lat373(4);
  w_14_q <= 'Z' when oe373 = '1' else latch_lat373(5);
  w_15_q <= 'Z' when oe373 = '1' else latch_lat373(6);
  w_16_q <= 'Z' when oe373 = '1' else latch_lat373(7);
  -- 74HC374 reg374
  process(clk374)
  begin
    if rising_edge(clk374) then
      reg_reg374 <= w_0 & w_0 & w_0 & w_21 & w_20 & w_19 & w_18 & w_17;
    end if;
  end process; -- 74HC374 reg374
  w_22_q <= 'Z' when oe374 = '1' else reg_reg374(0);
  w_23_q <= 'Z' when oe374 = '1' else reg_reg374(1);
  w_24_q <= 'Z' when oe374 = '1' else reg_reg374(2);
  w_25_q <= 'Z' when oe374 = '1' else reg_reg374(3);
  w_26_q <= 'Z' when oe374 = '1' else reg_reg374(4);
  w_reg374_q5 <= 'Z' when oe374 = '1' else reg_reg374(5);
  w_reg374_q6 <= 'Z' when oe374 = '1' else reg_reg374(6);
  w_reg374_q7 <= 'Z' when oe374 = '1' else reg_reg374(7);

end Behavioral;