// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_3_shift_pipeline (
  input  wire clk,
  input  wire clrn,
  input  wire s0,
  input  wire s1,
  input  wire sr,
  input  wire sl,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  input  wire stcp,
  input  wire mr,
  input  wire oe,
  output wire w_0,
  output wire w_1,
  output wire w_2,
  output wire w_3,
  output wire w_4,
  output wire w_5,
  output wire w_6,
  output wire w_7,
  output wire w_8,
  output wire w_9,
  output wire w_10,
  output wire w_11
);

  reg [3:0] reg_dut_194;
  reg [7:0] shift_dut_595;
  reg [7:0] latch_dut_595;

  // Sequential logic
  // 74HC194 dut_194
  always @(posedge clk or negedge clrn) begin
    if (!clrn) reg_dut_194 <= 4'b0;
    else case ({s1, s0})
      2'b01: reg_dut_194 <= {sr, reg_dut_194[3:1]};
      2'b10: reg_dut_194 <= {reg_dut_194[2:0], sl};
      2'b11: reg_dut_194 <= {d3,d2,d1,d0};
      default: ;
    endcase
  end // 74HC194 dut_194
  assign w_0 = reg_dut_194[0];
  assign w_1 = reg_dut_194[1];
  assign w_2 = reg_dut_194[2];
  assign w_3 = reg_dut_194[3];
  // 74HC595 dut_595
  always @(posedge clk or negedge mr) begin
    if (!mr) shift_dut_595 <= 8'b0;
    else        shift_dut_595 <= {shift_dut_595[6:0], w_3};
  end
  always @(posedge stcp) begin
    latch_dut_595 <= shift_dut_595;
  end // 74HC595 dut_595
  assign w_4 = oe ? 1'bz : latch_dut_595[0];
  assign w_5 = oe ? 1'bz : latch_dut_595[1];
  assign w_6 = oe ? 1'bz : latch_dut_595[2];
  assign w_7 = oe ? 1'bz : latch_dut_595[3];
  assign w_8 = oe ? 1'bz : latch_dut_595[4];
  assign w_9 = oe ? 1'bz : latch_dut_595[5];
  assign w_10 = oe ? 1'bz : latch_dut_595[6];
  assign w_11 = oe ? 1'bz : latch_dut_595[7];

endmodule // gc_v2_3_shift_pipeline
`default_nettype wire