// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_14_mixed_datapath_extended (
  input  wire b0,
  input  wire b1,
  input  wire b2,
  input  wire b3,
  input  wire op0,
  input  wire op1,
  input  wire op2,
  input  wire cin,
  input  wire clk,
  input  wire rst,
  input  wire en,
  output reg  w_8,
  output reg  w_9,
  output reg  w_10,
  output reg  w_11
);

  wire w_0, w_1, w_2, w_3, w_ctr_rco;

  reg  w_4, w_5, w_6, w_7, w_alu_cout, w_alu_zero;

  reg [3:0] cnt_ctr;

  // ALU4 alu
  always @(*) begin : blk_alu
    reg [3:0] va, vb;
    reg [4:0] sum;
    va  = {w_3, w_2, w_1, w_0};
    vb  = {b3, b2, b1, b0};
    sum = 5'b0;
    case ({op2, op1, op0})
      3'b000: sum = {1'b0, va} + {1'b0, vb} + {4'b0, cin}; // ADD
      3'b001: sum = {1'b0, va} - {1'b0, vb} - {4'b0, cin}; // SUB
      3'b010: sum = {1'b0, va & vb};                           // AND
      3'b011: sum = {1'b0, va | vb};                           // OR
      3'b100: sum = {1'b0, va ^ vb};                           // XOR
      3'b101: sum = {1'b0, ~va};                               // NOT A
      3'b110: sum = {va, 1'b0};                                // SHL (MSB→COUT)
      3'b111: sum = {va[0], 1'b0, va[3:1]};                   // SHR (LSB→COUT)
      default: sum = 5'b0;
    endcase
    w_4 = sum[0]; w_5 = sum[1]; w_6 = sum[2]; w_7 = sum[3];
    w_alu_cout = sum[4];
    w_alu_zero = (sum[3:0] == 4'b0) ? 1'b1 : 1'b0;
  end // ALU4 alu

  // Sequential logic
  // BIN_CTR7S ctr
  always @(posedge clk or posedge rst) begin
    if (rst)     cnt_ctr <= 4'd0;
    else if (en) cnt_ctr <= cnt_ctr + 1'b1;
  end // BIN_CTR7S ctr
  assign w_0  = cnt_ctr[0];
  assign w_1  = cnt_ctr[1];
  assign w_2  = cnt_ctr[2];
  assign w_3  = cnt_ctr[3];
  assign w_ctr_rco = (cnt_ctr == 4'd15) ? 1'b1 : 1'b0;
  // REG4 reg
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_8 <= 1'b0; w_9 <= 1'b0; w_10 <= 1'b0; w_11 <= 1'b0;
    end else if (en) begin
      w_8 <= w_4; w_9 <= w_5; w_10 <= w_6; w_11 <= w_7;
    end
  end // REG4 reg

endmodule // gc_v2_14_mixed_datapath_extended
`default_nettype wire