// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_10_custom_tribuf_wrap (
  input  wire a,
  input  wire oe,
  output wire w_0
);

  // TRIBUF tri_wrap_flat_dut
  assign w_0 = (~oe) ? a : 1'bz;

endmodule // gc_v2_10_custom_tribuf_wrap
`default_nettype wire