-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_10_custom_tribuf_wrap is
  Port (
    a : in STD_LOGIC;
    oe : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end gc_v2_10_custom_tribuf_wrap;

architecture Behavioral of gc_v2_10_custom_tribuf_wrap is
  signal w_0_q : STD_LOGIC := '0';
begin

  -- TRIBUF tri_wrap_flat_dut
  w_0_q <= a when oe = '0' else 'Z';

  w_0 <= w_0_q;

end Behavioral;