// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_4_ram_readback (
  input  wire a0,
  input  wire a1,
  input  wire a2,
  input  wire a3,
  input  wire a4,
  input  wire a5,
  input  wire a6,
  input  wire a7,
  input  wire di0,
  input  wire di1,
  input  wire di2,
  input  wire di3,
  input  wire di4,
  input  wire di5,
  input  wire di6,
  input  wire di7,
  input  wire we,
  input  wire cs,
  input  wire oe,
  input  wire clk,
  input  wire rst,
  output reg  w_0,
  output reg  w_1,
  output reg  w_2,
  output reg  w_3,
  output reg  w_4,
  output reg  w_5,
  output reg  w_6,
  output reg  w_7,
  output reg  w_8
);

  reg  w_9, w_10, w_11, w_12, w_13, w_14, w_15;

  reg [7:0] ram_ram [0:255];
  integer ram_ram_init_idx;
  initial begin
    for (ram_ram_init_idx = 0; ram_ram_init_idx < 256; ram_ram_init_idx = ram_ram_init_idx + 1) begin
      ram_ram[ram_ram_init_idx] = 8'h00;
    end
  end

  // RAM256 ram
  /* verilator lint_off LATCH */
  always @(*) begin // async write (transparent latch)
    if (cs == 1'b0 && we == 1'b0)
      ram_ram[{a7, a6, a5, a4, a3, a2, a1, a0}] = {di7, di6, di5, di4, di3, di2, di1, di0};
  end
  /* verilator lint_on LATCH */
  always @(*) begin // read
    if (cs == 1'b0 && oe == 1'b0)
      {w_15, w_14, w_13, w_12, w_11, w_10, w_9, w_8} = ram_ram[{a7, a6, a5, a4, a3, a2, a1, a0}];
    else
      {w_15, w_14, w_13, w_12, w_11, w_10, w_9, w_8} = 8'hzz;
  end // RAM256 ram

  // Sequential logic
  // REG8 reg
  always @(posedge clk or posedge rst) begin
    if (rst) begin
      w_0 <= 1'b0; w_1 <= 1'b0; w_2 <= 1'b0; w_3 <= 1'b0; w_4 <= 1'b0; w_5 <= 1'b0; w_6 <= 1'b0; w_7 <= 1'b0;
    end else begin
      w_0 <= w_8; w_1 <= w_9; w_2 <= w_10; w_3 <= w_11; w_4 <= w_12; w_5 <= w_13; w_6 <= w_14; w_7 <= w_15;
    end
  end // REG8 reg

endmodule // gc_v2_4_ram_readback
`default_nettype wire