-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_9_custom_reg4_pipeline is
  Port (
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    en : in STD_LOGIC;
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC;
    w_2 : out STD_LOGIC;
    w_3 : out STD_LOGIC;
    w_4 : out STD_LOGIC;
    w_5 : out STD_LOGIC;
    w_6 : out STD_LOGIC;
    w_7 : out STD_LOGIC;
    w_8 : out STD_LOGIC
  );
end gc_v2_9_custom_reg4_pipeline;

architecture Behavioral of gc_v2_9_custom_reg4_pipeline is
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal w_2_q : STD_LOGIC := '0';
  signal w_3_q : STD_LOGIC := '0';
  signal w_4_q : STD_LOGIC := '0';
  signal w_5_q : STD_LOGIC := '0';
  signal w_6_q : STD_LOGIC := '0';
  signal w_7_q : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
begin

  w_8_q <= w_0_q xor w_4_q; -- cmp_xor

  w_0 <= w_0_q;
  w_1 <= w_1_q;
  w_2 <= w_2_q;
  w_3 <= w_3_q;
  w_4 <= w_4_q;
  w_5 <= w_5_q;
  w_6 <= w_6_q;
  w_7 <= w_7_q;
  w_8 <= w_8_q;

  -- Sequential / registered logic
  -- REG4 reg_a_flat_dut
  process(clk, rst)
  begin
    if rst = '1' then
      w_0_q <= '0'; w_1_q <= '0'; w_2_q <= '0'; w_3_q <= '0';
    elsif rising_edge(clk) then
      if en = '1' then
        w_0_q <= d0; w_1_q <= d1; w_2_q <= d2; w_3_q <= d3;
      end if;
    end if;
  end process; -- REG4 reg_a_flat_dut
  -- REG4 reg_b_flat_dut
  process(clk, rst)
  begin
    if rst = '1' then
      w_4_q <= '0'; w_5_q <= '0'; w_6_q <= '0'; w_7_q <= '0';
    elsif rising_edge(clk) then
      if en = '1' then
        w_4_q <= w_0_q; w_5_q <= w_1_q; w_6_q <= w_2_q; w_7_q <= w_3_q;
      end if;
    end if;
  end process; -- REG4 reg_b_flat_dut

end Behavioral;