// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module gc_v2_5_decode_tree (
  input  wire a,
  input  wire b,
  input  wire c,
  input  wire g1,
  input  wire g2a,
  input  wire g2b,
  input  wire ein,
  input  wire le373,
  input  wire oe373,
  input  wire clk374,
  input  wire oe374,
  output wire w_9,
  output wire w_10,
  output wire w_11,
  output wire w_12,
  output wire w_13,
  output wire w_14,
  output wire w_15,
  output wire w_16,
  output wire w_22,
  output wire w_23,
  output wire w_24,
  output wire w_25,
  output wire w_26
);

  wire w_0, w_1, w_2, w_3, w_4, w_5, w_6, w_7, w_8, w_17, w_18, w_19, w_20, w_21, w_reg374_q5, w_reg374_q6, w_reg374_q7;

  reg [7:0] latch_lat373;
  reg [7:0] reg_reg374;

  assign w_0 = 1'b0; // CONST_LOW
  // 74HC138 dec138
  assign w_1 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd0));
  assign w_2 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd1));
  assign w_3 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd2));
  assign w_4 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd3));
  assign w_5 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd4));
  assign w_6 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd5));
  assign w_7 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd6));
  assign w_8 = ~((g1 & ~g2a & ~g2b) & ({c, b, a} == 3'd7));
  // 74HC148 enc148
  wire       act_enc148 = ~w_8|~w_7|~w_6|~w_5|~w_4|~w_3|~w_2|~w_1;
  wire [2:0] pri_enc148 = ~w_8 ? 3'b000 : ~w_7 ? 3'b001 : ~w_6 ? 3'b010 : ~w_5 ? 3'b011 :
                          ~w_4 ? 3'b100 : ~w_3 ? 3'b101 : ~w_2 ? 3'b110 : 3'b111;
  assign w_17 = ein ? 1'b1 : (act_enc148 ? pri_enc148[0] : 1'b1);
  assign w_18 = ein ? 1'b1 : (act_enc148 ? pri_enc148[1] : 1'b1);
  assign w_19 = ein ? 1'b1 : (act_enc148 ? pri_enc148[2] : 1'b1);
  assign w_20 = ein | ~act_enc148;
  assign w_21 = ein | act_enc148;

  // Sequential logic
  // 74HC373 lat373
  /* verilator lint_off LATCH */
  always @(*) begin
    if (le373) latch_lat373 = {w_8,w_7,w_6,w_5,w_4,w_3,w_2,w_1};
  end /* verilator lint_on LATCH */ // 74HC373 lat373
  assign w_9 = oe373 ? 1'bz : latch_lat373[0];
  assign w_10 = oe373 ? 1'bz : latch_lat373[1];
  assign w_11 = oe373 ? 1'bz : latch_lat373[2];
  assign w_12 = oe373 ? 1'bz : latch_lat373[3];
  assign w_13 = oe373 ? 1'bz : latch_lat373[4];
  assign w_14 = oe373 ? 1'bz : latch_lat373[5];
  assign w_15 = oe373 ? 1'bz : latch_lat373[6];
  assign w_16 = oe373 ? 1'bz : latch_lat373[7];
  // 74HC374 reg374
  always @(posedge clk374) begin
    reg_reg374 <= {w_0,w_0,w_0,w_21,w_20,w_19,w_18,w_17};
  end // 74HC374 reg374
  assign w_22 = oe374 ? 1'bz : reg_reg374[0];
  assign w_23 = oe374 ? 1'bz : reg_reg374[1];
  assign w_24 = oe374 ? 1'bz : reg_reg374[2];
  assign w_25 = oe374 ? 1'bz : reg_reg374[3];
  assign w_26 = oe374 ? 1'bz : reg_reg374[4];
  assign w_reg374_q5 = oe374 ? 1'bz : reg_reg374[5];
  assign w_reg374_q6 = oe374 ? 1'bz : reg_reg374[6];
  assign w_reg374_q7 = oe374 ? 1'bz : reg_reg374[7];

endmodule // gc_v2_5_decode_tree
`default_nettype wire