-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity gc_v2_14_mixed_datapath_extended is
  Port (
    b0 : in STD_LOGIC;
    b1 : in STD_LOGIC;
    b2 : in STD_LOGIC;
    b3 : in STD_LOGIC;
    op0 : in STD_LOGIC;
    op1 : in STD_LOGIC;
    op2 : in STD_LOGIC;
    cin : in STD_LOGIC;
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    en : in STD_LOGIC;
    w_8 : out STD_LOGIC;
    w_9 : out STD_LOGIC;
    w_10 : out STD_LOGIC;
    w_11 : out STD_LOGIC
  );
end gc_v2_14_mixed_datapath_extended;

architecture Behavioral of gc_v2_14_mixed_datapath_extended is
  signal w_0 : STD_LOGIC := '0';
  signal w_1 : STD_LOGIC := '0';
  signal w_2 : STD_LOGIC := '0';
  signal w_3 : STD_LOGIC := '0';
  signal w_ctr_rco : STD_LOGIC := '0';
  signal w_4 : STD_LOGIC := '0';
  signal w_5 : STD_LOGIC := '0';
  signal w_6 : STD_LOGIC := '0';
  signal w_7 : STD_LOGIC := '0';
  signal w_alu_cout : STD_LOGIC := '0';
  signal w_alu_zero : STD_LOGIC := '0';
  signal w_8_q : STD_LOGIC := '0';
  signal w_9_q : STD_LOGIC := '0';
  signal w_10_q : STD_LOGIC := '0';
  signal w_11_q : STD_LOGIC := '0';
  signal cnt_ctr : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  -- ALU4 alu
  process(w_0, w_1, w_2, w_3, b0, b1, b2, b3, op0, op1, op2, cin)
    variable va  : unsigned(3 downto 0);
    variable vb  : unsigned(3 downto 0);
    variable vop : integer range 0 to 7;
    variable sum : unsigned(4 downto 0);
  begin
    va  := unsigned(STD_LOGIC_VECTOR'(w_3 & w_2 & w_1 & w_0));
    vb  := unsigned(STD_LOGIC_VECTOR'(b3 & b2 & b1 & b0));
    vop := to_integer(unsigned(STD_LOGIC_VECTOR'(op2 & op1 & op0)));
    sum := (others => '0');
    case vop is
      when 0 => sum := resize(va,5) + resize(vb,5) + (to_unsigned(0,4) & cin); -- ADD
      when 1 => sum := resize(va,5) - resize(vb,5) - (to_unsigned(0,4) & cin); -- SUB
      when 2 => sum(3 downto 0) := va and vb;                                   -- AND
      when 3 => sum(3 downto 0) := va or  vb;                                   -- OR
      when 4 => sum(3 downto 0) := va xor vb;                                   -- XOR
      when 5 => sum(3 downto 0) := not va;                                      -- NOT A
      when 6 => sum(0):='0'; sum(1):=va(0); sum(2):=va(1); sum(3):=va(2); sum(4):=va(3); -- SHL
      when 7 => sum(0):=va(1); sum(1):=va(2); sum(2):=va(3); sum(3):='0'; sum(4):=va(0); -- SHR
      when others => null;
    end case;
    w_4 <= sum(0); w_5 <= sum(1); w_6 <= sum(2); w_7 <= sum(3);
    w_alu_cout <= sum(4);
    if sum(3 downto 0) = x"0" then w_alu_zero <= '1'; else w_alu_zero <= '0'; end if;
  end process; -- ALU4 alu

  w_8 <= w_8_q;
  w_9 <= w_9_q;
  w_10 <= w_10_q;
  w_11 <= w_11_q;

  -- Sequential / registered logic
  -- BIN_CTR7S ctr
  process(clk, rst)
  begin
    if rst = '1' then
      cnt_ctr <= (others => '0');
    elsif rising_edge(clk) then
      if en = '1' then
        cnt_ctr <= std_logic_vector(unsigned(cnt_ctr) + 1);
      end if;
    end if;
  end process; -- BIN_CTR7S ctr
  w_0  <= cnt_ctr(0);
  w_1  <= cnt_ctr(1);
  w_2  <= cnt_ctr(2);
  w_3  <= cnt_ctr(3);
  w_ctr_rco <= '1' when cnt_ctr = "1111" else '0';
  -- REG4 reg
  process(clk, rst)
  begin
    if rst = '1' then
      w_8_q <= '0'; w_9_q <= '0'; w_10_q <= '0'; w_11_q <= '0';
    elsif rising_edge(clk) then
      if en = '1' then
        w_8_q <= w_4; w_9_q <= w_5; w_10_q <= w_6; w_11_q <= w_7;
      end if;
    end if;
  end process; -- REG4 reg

end Behavioral;