-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity hc373_oe_z is
  Port (
    oe : in STD_LOGIC;
    le : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    d4 : in STD_LOGIC;
    d5 : in STD_LOGIC;
    d6 : in STD_LOGIC;
    d7 : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end hc373_oe_z;

architecture Behavioral of hc373_oe_z is
  signal w_dut_q1 : STD_LOGIC := '0';
  signal w_dut_q2 : STD_LOGIC := '0';
  signal w_dut_q3 : STD_LOGIC := '0';
  signal w_dut_q4 : STD_LOGIC := '0';
  signal w_dut_q5 : STD_LOGIC := '0';
  signal w_dut_q6 : STD_LOGIC := '0';
  signal w_dut_q7 : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal latch_dut : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;

  -- Sequential / registered logic
  -- 74HC373 dut
  process(le, d0, d1, d2, d3, d4, d5, d6, d7)
  begin
    if le = '1' then
      latch_dut <= d7 & d6 & d5 & d4 & d3 & d2 & d1 & d0;
    end if;
  end process; -- 74HC373 dut
  w_0_q <= 'Z' when oe = '1' else latch_dut(0);
  w_dut_q1 <= 'Z' when oe = '1' else latch_dut(1);
  w_dut_q2 <= 'Z' when oe = '1' else latch_dut(2);
  w_dut_q3 <= 'Z' when oe = '1' else latch_dut(3);
  w_dut_q4 <= 'Z' when oe = '1' else latch_dut(4);
  w_dut_q5 <= 'Z' when oe = '1' else latch_dut(5);
  w_dut_q6 <= 'Z' when oe = '1' else latch_dut(6);
  w_dut_q7 <= 'Z' when oe = '1' else latch_dut(7);

end Behavioral;