// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module hc373_oe_z (
  input  wire oe,
  input  wire le,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  input  wire d4,
  input  wire d5,
  input  wire d6,
  input  wire d7,
  output wire w_0
);

  wire w_dut_q1, w_dut_q2, w_dut_q3, w_dut_q4, w_dut_q5, w_dut_q6, w_dut_q7;

  reg [7:0] latch_dut;

  // Sequential logic
  // 74HC373 dut
  always @(*) begin
    if (le) latch_dut = {d7,d6,d5,d4,d3,d2,d1,d0};
  end // 74HC373 dut
  assign w_0 = oe ? 1'bz : latch_dut[0];
  assign w_dut_q1 = oe ? 1'bz : latch_dut[1];
  assign w_dut_q2 = oe ? 1'bz : latch_dut[2];
  assign w_dut_q3 = oe ? 1'bz : latch_dut[3];
  assign w_dut_q4 = oe ? 1'bz : latch_dut[4];
  assign w_dut_q5 = oe ? 1'bz : latch_dut[5];
  assign w_dut_q6 = oe ? 1'bz : latch_dut[6];
  assign w_dut_q7 = oe ? 1'bz : latch_dut[7];

endmodule // hc373_oe_z
`default_nettype wire