// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module multi_driver_same_input (
  input  wire a,
  input  wire b,
  output wire b
);

endmodule // multi_driver_same_input
`default_nettype wire