-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity multi_driver_same_input is
  Port (
    a : in STD_LOGIC;
    b : in STD_LOGIC;
    b : out STD_LOGIC
  );
end multi_driver_same_input;

architecture Behavioral of multi_driver_same_input is
  signal b_q : STD_LOGIC := '0';
begin

  b <= b_q;

end Behavioral;