-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity tri_led_z is
  Port (
    a : in STD_LOGIC;
    oe : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end tri_led_z;

architecture Behavioral of tri_led_z is
  signal w_0_q : STD_LOGIC := '0';
begin

  -- TRIBUF tri
  w_0_q <= a when oe = '0' else 'Z';

  w_0 <= w_0_q;

end Behavioral;