-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity tri_not_sanitized is
  Port (
    a : in STD_LOGIC;
    oe : in STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end tri_not_sanitized;

architecture Behavioral of tri_not_sanitized is
  signal w_0 : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
begin

  -- TRIBUF tri
  w_0 <= a when oe = '0' else 'Z';
  w_1_q <= not w_0; -- inv

  w_1 <= w_1_q;

end Behavioral;