// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module tri_led_z (
  input  wire a,
  input  wire oe,
  output wire w_0
);

  // TRIBUF tri
  assign w_0 = (~oe) ? a : 1'bz;

endmodule // tri_led_z
`default_nettype wire