// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module tri_not_sanitized (
  input  wire a,
  input  wire oe,
  output wire w_1
);

  wire w_0;

  // TRIBUF tri
  assign w_0 = (~oe) ? a : 1'bz;
  not g_inv(w_1, w_0);

endmodule // tri_not_sanitized
`default_nettype wire