// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module dff_led (
  input  wire d,
  input  wire clk,
  output reg  w_0
);

  wire w_dut_q_n;

  // Sequential logic
  always @(posedge clk) begin
    w_0 <= d;
  end // D-FF dut
  assign w_dut_q_n = ~w_0;

endmodule // dff_led
`default_nettype wire