// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module hc163_clear (
  input  wire clk,
  input  wire clrn,
  input  wire ldn,
  input  wire enp,
  input  wire ent,
  input  wire d0,
  input  wire d1,
  input  wire d2,
  input  wire d3,
  output wire w_0,
  output wire w_1
);

  wire w_dut_q2, w_dut_q3, w_dut_rco;

  reg [3:0] cnt_dut;

  // Sequential logic
  // 74HC163 dut
  always @(posedge clk) begin
    if      (!clrn)               cnt_dut <= 4'd0;
    else if (!ldn)                cnt_dut <= {d3,d2,d1,d0};
    else if (enp && ent)       cnt_dut <= cnt_dut + 1'b1;
  end // 74HC163 dut
  assign w_0 = cnt_dut[0];
  assign w_1 = cnt_dut[1];
  assign w_dut_q2 = cnt_dut[2];
  assign w_dut_q3 = cnt_dut[3];
  assign w_dut_rco  = ent & (cnt_dut == 4'd15);

endmodule // hc163_clear
`default_nettype wire