-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity hc161_clear is
  Port (
    clk : in STD_LOGIC;
    clrn : in STD_LOGIC;
    ldn : in STD_LOGIC;
    enp : in STD_LOGIC;
    ent : in STD_LOGIC;
    d0 : in STD_LOGIC;
    d1 : in STD_LOGIC;
    d2 : in STD_LOGIC;
    d3 : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end hc161_clear;

architecture Behavioral of hc161_clear is
  signal w_dut_q2 : STD_LOGIC := '0';
  signal w_dut_q3 : STD_LOGIC := '0';
  signal w_dut_rco : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal cnt_dut : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;

  -- Sequential / registered logic
  -- 74HC161 dut
  process(clk, clrn)
  begin
    if    clrn = '0'             then cnt_dut <= (others => '0');
    elsif rising_edge(clk) then
      if    ldn  = '0'                       then cnt_dut <= d3 & d2 & d1 & d0;
      elsif enp  = '1' and ent = '1'      then cnt_dut <= std_logic_vector(unsigned(cnt_dut) + 1);
      end if;
    end if;
  end process; -- 74HC161 dut
  w_0_q <= cnt_dut(0);
  w_1_q <= cnt_dut(1);
  w_dut_q2 <= cnt_dut(2);
  w_dut_q3 <= cnt_dut(3);
  w_dut_rco  <= ent when unsigned(cnt_dut) = 15 else '0';

end Behavioral;