-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity hc595_oe_shift is
  Port (
    ds : in STD_LOGIC;
    shcp : in STD_LOGIC;
    stcp : in STD_LOGIC;
    mr : in STD_LOGIC;
    oe : in STD_LOGIC;
    w_0 : out STD_LOGIC;
    w_1 : out STD_LOGIC
  );
end hc595_oe_shift;

architecture Behavioral of hc595_oe_shift is
  signal w_dut_q2 : STD_LOGIC := '0';
  signal w_dut_q3 : STD_LOGIC := '0';
  signal w_dut_q4 : STD_LOGIC := '0';
  signal w_dut_q5 : STD_LOGIC := '0';
  signal w_dut_q6 : STD_LOGIC := '0';
  signal w_dut_q7 : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
  signal w_1_q : STD_LOGIC := '0';
  signal shift_dut : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
  signal latch_dut : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
begin

  w_0 <= w_0_q;
  w_1 <= w_1_q;

  -- Sequential / registered logic
  -- 74HC595 dut
  process(shcp, mr)
  begin
    if mr = '0' then shift_dut <= (others => '0');
    elsif rising_edge(shcp) then shift_dut <= shift_dut(6 downto 0) & ds;
    end if;
  end process;
  process(stcp)
  begin
    if rising_edge(stcp) then latch_dut <= shift_dut;
    end if;
  end process; -- 74HC595 dut
  w_0_q <= 'Z' when oe = '1' else latch_dut(0);
  w_1_q <= 'Z' when oe = '1' else latch_dut(1);
  w_dut_q2 <= 'Z' when oe = '1' else latch_dut(2);
  w_dut_q3 <= 'Z' when oe = '1' else latch_dut(3);
  w_dut_q4 <= 'Z' when oe = '1' else latch_dut(4);
  w_dut_q5 <= 'Z' when oe = '1' else latch_dut(5);
  w_dut_q6 <= 'Z' when oe = '1' else latch_dut(6);
  w_dut_q7 <= 'Z' when oe = '1' else latch_dut(7);

end Behavioral;