// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module hc595_oe_shift (
  input  wire ds,
  input  wire shcp,
  input  wire stcp,
  input  wire mr,
  input  wire oe,
  output wire w_0,
  output wire w_1
);

  wire w_dut_q2, w_dut_q3, w_dut_q4, w_dut_q5, w_dut_q6, w_dut_q7;

  reg [7:0] shift_dut;
  reg [7:0] latch_dut;

  // Sequential logic
  // 74HC595 dut
  always @(posedge shcp or negedge mr) begin
    if (!mr) shift_dut <= 8'b0;
    else        shift_dut <= {shift_dut[6:0], ds};
  end
  always @(posedge stcp) begin
    latch_dut <= shift_dut;
  end // 74HC595 dut
  assign w_0 = oe ? 1'bz : latch_dut[0];
  assign w_1 = oe ? 1'bz : latch_dut[1];
  assign w_dut_q2 = oe ? 1'bz : latch_dut[2];
  assign w_dut_q3 = oe ? 1'bz : latch_dut[3];
  assign w_dut_q4 = oe ? 1'bz : latch_dut[4];
  assign w_dut_q5 = oe ? 1'bz : latch_dut[5];
  assign w_dut_q6 = oe ? 1'bz : latch_dut[6];
  assign w_dut_q7 = oe ? 1'bz : latch_dut[7];

endmodule // hc595_oe_shift
`default_nettype wire