// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module jkff_led (
  input  wire j,
  input  wire k,
  input  wire clk,
  output reg  w_0
);

  wire w_dut_q_n;

  // Sequential logic
  always @(posedge clk) begin
    if      (j && !k) w_0 <= 1'b1;
    else if (!j && k) w_0 <= 1'b0;
    else if (j && k)  w_0 <= ~w_0;
  end // JK-FF dut
  assign w_dut_q_n = ~w_0;

endmodule // jkff_led
`default_nettype wire