-- Generated by LogicSim
-- HDL EXPORT BLOCKED — multi-driver port conflict
-- The following signal(s) appear as both input and output port:
-- conflicting signal: "b"
-- Each destination port must have exactly one driver.
-- Resolve bus contention before exporting to HDL.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity multi_driver_same_input is
  -- no ports — export blocked due to multi-driver conflict
end multi_driver_same_input;

architecture Behavioral of multi_driver_same_input is
begin
  -- no logic — export blocked due to multi-driver conflict
end Behavioral;