// Generated by LogicSim
// HDL EXPORT BLOCKED — multi-driver port conflict
// The following signal(s) appear as both input and output port:
// conflicting signal: "b"
// Each destination port must have exactly one driver.
// Resolve bus contention before exporting to HDL.
`default_nettype none

module multi_driver_same_input;
  // no logic — export blocked due to multi-driver conflict
endmodule // multi_driver_same_input
`default_nettype wire