-- Generated by LogicSim
-- VHDL-2002 — bit 0 = LSB

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity tff_led is
  Port (
    t : in STD_LOGIC;
    clk : in STD_LOGIC;
    w_0 : out STD_LOGIC
  );
end tff_led;

architecture Behavioral of tff_led is
  signal w_dut_q_n : STD_LOGIC := '0';
  signal w_0_q : STD_LOGIC := '0';
begin

  w_0 <= w_0_q;

  -- Sequential / registered logic
  process(clk)
  begin
    if rising_edge(clk) then
      if t = '1' then w_0_q <= not w_0_q; end if;
    end if;
  end process; -- T-FF dut
  w_dut_q_n <= not w_0_q;

end Behavioral;