// Generated by LogicSim
// Verilog-2001 — bit 0 = LSB
`default_nettype none

module tff_led (
  input  wire t,
  input  wire clk,
  output reg  w_0
);

  wire w_dut_q_n;

  // Sequential logic
  always @(posedge clk) begin
    if (t) w_0 <= ~w_0;
  end // T-FF dut
  assign w_dut_q_n = ~w_0;

endmodule // tff_led
`default_nettype wire